### ISSUE TITLE
Generated code does not respect allOf with required fields

### ISSUE THREAD

**Issue by berkowitzi** [koxudaxi/datamodel-code-generator#1009]
**Describe the bug**
If you are using a base schema with optional fields plus extension schemas that require certain fields, the generated code still simply inherits from the base schema without marking the relevant fields as required.

**To Reproduce**

Example schema:
```yaml
components:
  schemas:
    ObjectBase:
      description: Object schema
      type: object
      properties:
        name:
          description: Name of the object
          type: string
        type:
          description: Object type
          type: string
          enum:
            - my_first_object
            - my_second_object
    CreateObjectRequest:
      description: Request schema for object creation
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectBase'
      required:
        - name
        - type
    UpdateObjectRequest:
      description: Request schema for object updates
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectBase'
```

Used commandline:
```
$ datamodel-codegen --input openapi.yaml --target-python-version=3.9
```

**Expected behavior**
I'd expect to see a CreateObjectRequest schema that *does not* have name and type as optional.

**Version:**
 - Python version: 3.10.4
 - datamodel-code-generator version: 0.15.0

**Additional context**

**Comment by koxudaxi** [comment]
@berkowitzi   
I have released the fixed version `0.16.0`
Thank you very much!!
