### ISSUE TITLE
--capitalise-enum-members is over-eager

### ISSUE THREAD

**Issue by berkowitzi** [koxudaxi/datamodel-code-generator#1010]
**Describe the bug**
`--capitalise-enum-members` does capitalize enum members, but it also capitalizes some kwarg names, plus object property names.

**To Reproduce**

Example generated class:
```python
class Type(Enum):
    OBJECT_TYPE_ONE = "object_type_one"


class ObjectBase(BaseModel):
    NAME: Optional[str] = Field(None, DESCRIPTION="Name for the object", alias="name")
    TYPE: Optional[Type] = Field(None, DESCRIPTION="Object type", alias="type")
```

Used commandline:
```
$ --input client/openapi.yaml \
  --target-python-version=3.9 \
  --input-file-type openapi \
  --validation \
  --capitalise-enum-members
```

**Expected behavior**
Only enum member names are capitalised.

**Version:**
 - OS: [e.g. iOS] MacOS
 - Python version: 3.10.4
 - datamodel-code-generator version: 0.15.0

**Additional context**

**Comment by koxudaxi** [comment]
@berkowitzi   
I have released the fixed version `0.16.0`
Thank you very much!!
