### ISSUE TITLE
The underlying validation library is broken/unmaintained.

### ISSUE THREAD

**Issue by pkucmus** [koxudaxi/datamodel-code-generator#105]
p1c2u/openapi-spec-validator as great as it is, does not properly validate valid OpenAPI 3 specs (at least not all of them) - since model generation relies on validation this library is also "broken" (I tried to avoid this word but my English is not good enough)

The solution could be:
1. us taking matters in our own hands
2. using a proper validation tool like https://www.npmjs.com/package/swagger-parser. I am super uneasy with mixing JS with Python but nowadays running a tool in a pre-made container is a valid option
3. port the thing to Python
It's easy to say but I am only capable of doing the second. What you think?

datamodel-code-generator is at this point needed by the Internet - being able to generate FastAPI definitions from OpenAPI 3 will make backend PyDev work much easier and API first is generally a good approach.

Like I said I'm not capable enough of making it on my own - maybe together will be able to figure things out. If you see this "issue" valid of course.

**Comment by koxudaxi** [comment]
@pkucmus 
Thank you for creating this issue.

Interesting. I have not known that `p1c2u/openapi-spec-validator ` doesn't cover all OpenAPI Spec 3.

I feel good about the choice.
>1. us taking matters in our own hands

I would validate an OpenAPI file by the library. However, The feature doesn't need on `datamodel-code-generator`.
`datamodel-code-generator` is code-generator, It is not `validator`. (some users should use other tools like swagger-parser)

Also, `datamodel-code-generator` parse an OpenAPI file as raw YAML or json file.
We can remove the dependency on `p1c2u/openapi-spec-validator `.
Or we can leave the feature as a command-line option. 

How do think about it?


> since model generation relies on validation this library is also "broken" (I tried to avoid this word but my English is not good enough)

No problem, The word is clear to me.
I always don't write English well. But, Online communities accept my bad English than the real world :smile:

**Comment by pkucmus** [comment]
I think that making the validation optional would be the way to go, by a `--no-validate/--validate` option, maybe? 
Then there's the fact that we are lacking a proper OpenAPI 3 validator for Python but it's not an issue of this project.

**Comment by koxudaxi** [comment]
@pkucmus 
I have released a new version as  `0.4.1`.
I change the validation feature to optional.
If you add `--validation` on the CLI option then the code-generator validates an OpenAPI file.
