### ISSUE TITLE
Generation fails on parsing object definition wi "AnyOf" that contains "required"

### ISSUE THREAD

**Issue by truemetal74** [koxudaxi/datamodel-code-generator#1101]
**Describe the bug**
When parsing an OpenAPI schema that has "required" elements inside of "AnyOf", generation fails with an error:

```
  File "/home/andrew/my/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1094, in parse_root_type
    data_type = data_types[0]
                ~~~~~~~~~~^^^
IndexError: list index out of range
```

**To Reproduce**
run datamodel-codegen using the attached input file (I reduced it to the bare minimum to simplify the troubleshooting)

[test-yaml.zip](https://github.com/koxudaxi/datamodel-code-generator/files/10695800/test-yaml.zip)

Example schema:
```   IMSAddress:
      type: object
      properties:
        ipv4Addr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv4Addr'
        ipv6Addr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv6Addr'
        e164:
          $ref: '#/components/schemas/E164'
      anyOf:
        - required: [ ipv4Addr ]
        - required: [ ipv6Addr ]
        - required: [ e164 ]
 ```
The full file is [here](https://github.com/jdegre/5GC_APIs/blob/Rel-18/TS32291_Nchf_ConvergedCharging.yaml)

Used commandline:
```
datamodel-codegen  --input TS32291_Nchf_ConvergedCharging.yaml  --output /vagrant/nchf --input-file-type openapi --output-model-type pydantic.BaseModel  --use-schema-description --use-field-description --target-python-version 3.11
```

**Expected behavior**
A schema, that contains a definition of IMSAddress object with 3 attributes, something like
```
class IMSAddress(BaseModel):
  ipv4Addr: Optional[Ipv4Addr] = None
  ipv6Addr: Optional[ipv6Addr] = None
  e164: Optional[E164] = None
```

**Version:**
 - OS: OEL (RedHat) 7.9
 - Python version: 3.11
 - datamodel-code-generator version: latest from github, in the code it says `version: str = '0.0.0'`

**Additional context**
The problem is that the code in jsonschema.py (lines 1091-94) does not handle the situation when data_types list is empty :-(

```
            if len(data_types) > 1:
                data_type = self.data_type(data_types=data_types)
            else:  # pragma: no cover
                data_type = data_types[0]
```

**Comment by koxudaxi** [comment]
@truemetal74 
I have released the fixed version `0.17.2`
Thank you very much!!
