### ISSUE TITLE
Path to schema file in the $ref field doesn't recognize correctly

### ISSUE THREAD

**Issue by catcombo** [koxudaxi/datamodel-code-generator#1161]
**Describe the bug**

There is a bug with the `$ref` field if it points to the schema file in the same folder, but they both located in the nested folder.

**To Reproduce**

I prepared a repository with a minimal code to reproduce the issue https://github.com/catcombo/datamodel-codegen-ref-bug

**Expected behavior**

**Version:**
 - OS: Fedora 36
 - Python version: 3.10.10
 - datamodel-code-generator version: 0.17.1

**Additional context**

**Comment by koxudaxi** [comment]
@catcombo 
Thank you for creating the issue.
I have released the fixed version as 0.19.0.

**Comment by catcombo** [comment]
It works now! Thank you for fixing the bug! :kissing_cat:
