### ISSUE TITLE
Set max string lenght

### ISSUE THREAD

**Issue by DFilyushin** [koxudaxi/datamodel-code-generator#1183]
Every time when I run code-generator, I receive 80-char string length with wrapping string. But our Python style guide is about 120 char string length.

Could you add setup for string length?

Small example:

```
class Person(TypingModel):
    name_last: Optional[str] = Field(None, alias='nameLast', x_is_personal_data='true')
    name_first: Optional[str] = Field(
        None, alias='nameFirst', x_is_personal_data='true'
    )
    name_middle: Optional[str] = Field(
        None, alias='nameMiddle', x_is_personal_data='true'
    )
    birth_date: Optional[date] = Field(
        None, alias='birthDate', x_is_personal_data='true'
    )
    birth_place: Optional[str] = Field(
        None, alias='birthPlace', x_is_personal_data='true'
    )
    gender: Optional[Gender] = None
```

**Comment by koxudaxi** [comment]
@DFilyushin 
datamodel-code-generator uses black as a formatter.
We can define the black config in pyproject.toml.
https://koxudaxi.github.io/datamodel-code-generator/formatting/

Can you resolve the problem?

**Comment by koxudaxi** [comment]
no response
