### ISSUE TITLE
(🎁) Can we use heuristics to automatically detect the input type of json files?

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/datamodel-code-generator#1221]
It would be convenient if json files could be automatically detected if they are either schema or data files.

input:
```json
{
  "a": 1
}
```

```
👉 datamodel_code_generator --input test.json
# generated by datamodel-codegen:
#   filename:  test.json
#   timestamp: 2023-04-15T04:05:21+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
```

**Comment by KotlinIsland** [comment]
https://github.com/koxudaxi/datamodel-code-generator/blob/b48cb94edc76851eca0ff637bf81831330ea5808/datamodel_code_generator/__init__.py#L301-L310

So here we use check if the file is an OpenAPI, but could we do an additional check to see if the file is not a schema at all, but just a normal json file?

**Comment by koxudaxi** [comment]
@KotlinIsland 
How can we recognize whether JSON Schema or JSON data?
If we apply the strict rule, current behavior will be broken.
I think some use `auto` to convert rough JSON Schema :thinking:

**Comment by KotlinIsland** [comment]
Yes, I'm not certain if it's possible to determine if a file is schema or data.
