### ISSUE TITLE
Add `TypedDict` as a possible output model type

### ISSUE THREAD

**Issue by kylebebak** [koxudaxi/datamodel-code-generator#1229]
**Is your feature request related to a problem? Please describe.**

There are use cases where using a `TypedDict` makes more sense than a Pydantic model or a dataclass. For example, let's say you have a dict that was passed by an API client in the request body. Maybe you've already validated it using JSON Schema, so you don't need to validate it again using Pydantic. You want type hints on the dict... In this case, you'd want to use a `TypedDict`

**Describe the solution you'd like**

Add `typing.TypedDict` as one of the possible output model types, in addition to `{pydantic.BaseModel,dataclasses.dataclass}`. I'm guessing this can use much of the same machinery used to output Pydantic models and dataclasses. The syntax for `TypedDict`s is similar, and often nearly identical, e.g.

```py
from typing import TypedDict

from pydantic import BaseModel


class Rect(BaseModel):
    w: int
    h: int
    x: int
    y: int


class Rect(TypedDict):
    w: int
    h: int
    x: int
    y: int
```

Ideally the generated `TypedDict`s [could take advantage of `TypedDict`-only features](https://github.com/pydantic/pydantic/discussions/3563), like `NotRequired`

**Describe alternatives you've considered**

The alternative is using a Pydantic model or dataclass in place of `TypedDict`, but this isn't always ideal

**Comment by koxudaxi** [comment]
@kylebebak 
I have released the new version as `0.20.0`
Thank you very much!!
