### ISSUE TITLE
Support Generating Class Names From Path OperationId

### ISSUE THREAD

**Issue by zach-hamm** [koxudaxi/datamodel-code-generator#1260]
**Is your feature request related to a problem? Please describe.**
I really enjoy this generator and I'm excited to integrate it with my projects. The one issue I've ran into is with regards to the class names that are generated from OpenAPI specs, specifically for paths. At the moment, it looks like the class names are generated as `<route as camel case><method><suffix>` which works, but it's not great for more complicated routes.

For example, let's say I have the following spec file:

```
paths:
    /users/{user_id}/user_data:
        get:
            requestBody:
               ....
```

The resulting class from this generator is pretty hard to look at...

```
UsersUserIdUserDataGetRequest
```

**Describe the solution you'd like**
I think it would be great if you could add an arg for using the operationId in the OpenAPI spec instead. For example, if I update the schema above:

```
paths:
    /users/{user_id}/user_data:
        get:
            operationId: getUserData
            requestBody:
               ....
```

The class name on the output could then be easier to read like

```
GetUserDataRequest
```

**Describe alternatives you've considered**
None :(

**Additional context**
I already tried making the pull request myself, but I'm on a work computer and my git config wasn't allowing me to authenticate normally so here we are 😢 Instead, I've added what I believe would be necessary for this change and it's actually quite small.

[parser/openapi.py](https://github.com/koxudaxi/datamodel-code-generator/blob/2c57e397eb8549827e5fc8462937d10b8e4a4365/datamodel_code_generator/parser/openapi.py#L484) - add the condition below setting the path_name.
```python
path_name, method = path[-2:]
if self.use_operation_id_as_name:
    if not operation.operationId:
        raise Exception(
            f'All operations must have an operationId when --use_operation_id_as_name is set.'
            f'The following path was missing an operationId: {path_name}')
    path_name = operation.operationId
    method = ''
```

Apart from that, I believe you'd just need to setup the arg for `--use-operation-id-as-name`

**Comment by koxudaxi** [comment]
@zach-hamm 
I'm sorry for the late reply.
I apply your code to the main.
And I released the new version  `0.18.1`.
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.18.1

Thank you very much!!
