### ISSUE TITLE
Support for `msgspec.Struct` types as `--output-model-type`

### ISSUE THREAD

**Issue by jcrist** [koxudaxi/datamodel-code-generator#1278]
Hello! First off - thanks for all your work on `datamodel-code-generator`, it's an impressive and useful piece of software.

I maintain [msgspsec](https://github.com/jcrist/msgspec), a fast JSON serialization and validation library, which offers similar (but much faster) functionality as Pydantic. We've had [a request](https://github.com/jcrist/msgspec/issues/390) to be able to generate `msgspec.Struct` types from existing json-schema definitions. I *think* the easiest way to do this would be to add `msgspec` integration into `datamodel-code-generator` as an `--output-model-type`. Is this a feature you'd be interested in supporting?

I'd be happy to help/do the work, although if I make the PR myself I'll likely need some guidance. `msgspec.Struct` types are closer to `dataclasses` than `pydantic.BaseModel` types, given you support both of them I'd *hope* many of the code paths could already be reused and adding an additional model type wouldn't be too onerous.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/koxudaxi/datamodel-code-generator/issues/1278">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/koxudaxi/datamodel-code-generator/issues/1278/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/koxudaxi/datamodel-code-generator/issues/1278/pledge.svg">
</picture>
</a>

**Comment by koxudaxi** [comment]
@jcrist 
Thank you for creating the issue.
I learned about your project for the first time, and it's cool :)

OK, I'm happy if you create the PR and I will help you.

We need to write some code for constraints.
https://jcristharif.com/msgspec/constraints.html#constraints

**Comment by koxudaxi** [comment]
@jcrist 
The latest version supports `msgspec.Struct`
Thank you very much!!

**Comment by jcrist** [comment]
Thanks!
