### ISSUE TITLE
Missed schema when jsonschema has allOf-anyOf combination.

### ISSUE THREAD

**Issue by itaru2622** [koxudaxi/datamodel-code-generator#1289]
**Describe the bug**
Missed schema of property when jsonschema has allOf-anyOf combination.

**To Reproduce**

Example schema:

case1: all described in single definition (no $ref)
```json
{
  "definitions": {
    "Target": {
      "allOf": [
        {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "first": {
                  "type": "string"
                }
              },
              "required": [
                "first"
              ]
            },
            {
              "type": "object",
              "properties": {
                "second": {
                  "type": "string"
                }
              },
              "required": [
                "second"
              ]
            }
          ]
        },
        {
          "properties": {
            "third": {
              "type": "string"
            }
          },
          "required": [
            "third"
          ]
        }
      ]
    }
  }
}
```
case2:  definition with 'ref'
```json
{
  "definitions": {
    "First": {
      "properties": {
        "first": {
          "type": "string"
        }
      },
      "required": [
        "first"
      ]
    },
    "Second": {
      "properties": {
        "second": {
          "type": "string"
        }
      },
      "required": [
        "second"
      ]
    },
    "Target": {
      "allOf": [
        {
          "anyOf": [
            {
              "$ref": "#/definitions/First"
            },
            {
              "$ref": "#/definitions/Second"
            }
          ]
        },
        {
          "properties": {
            "third": {
              "type": "string"
            }
          },
          "required": [
            "third"
          ]
        }
      ]
    }
  }
}

```

Used commandline:
```
$ datamodel-codegen  --input-file-type jsonschema  --input file.json
```

**Generated result**

at case1:
```python
from __future__ import annotations
from pydantic import BaseModel

class Target(BaseModel):
    third: str
```

at case2:
```python
from __future__ import annotations
from pydantic import BaseModel

class First(BaseModel):
    first: str
class Second(BaseModel):
    second: str
class Target(BaseModel):
    third: str

```
**Expected behavior**
I expect, in both cases, Target model has inheritance of  First or Second model, something like below.

```python
:
class TargetAnyof(BaseModel):
    __root__: Union[First, Second]
class Target(TargetAnyof):
    third: str
```

When I tested just 'anyof' part (without allof), the result has Union[first,second] as  expeced. so, something wrong in processing the combination of allof and anyof, maybe in parser/jsonschema.py

**Version:**
 - OS: debian 11
 - Python version: 3.11 (with docker image python:3.11-bullseye)
 - datamodel-code-generator version:  0.18.1 and also latest master (hash: 45d3319)

**Comment by itaru2622** [comment]
@koxudaxi on debuging parse_all_of function in parser/jsonschema.py, I thougt _parse_all_of_item has to care about container types( anyOf, oneOf, etc) within the item like below but not sure how it achived.

https://github.com/koxudaxi/datamodel-code-generator/blob/12b202b98237b4e2b9692e218817cc53a2360305/datamodel_code_generator/parser/jsonschema.py#L701-L702

It may need to add base_classes when anyOf or oneOf found within the item...

**Comment by koxudaxi** [comment]
@itaru2622 
Thank you for creating the issue.
I understand the issue.

```python
:
class TargetAnyof(BaseModel):
    __root__: Union[First, Second]
class Target(TargetAnyof):
    third: str
```
Pydantic can't inherit a custom root model with an additional field.
We must extract TargetAnyof fields and combine additional fields.

**Comment by itaru2622** [comment]
@koxudaxi thank you for comment, then it needs to create multiple models as below in somehow...

```python
# besides class First(BaseModel) and class Sencond(BaseModel), it needs:

class ThirdItem(BaseModel):
    third: str
class TargetAnyofFirst_andThird(First,ThirdItem):
    pass
class TargetAnyofSecond_andThird(Second,ThirdItem):
    pass
class Target(BaseModel):
    __root__: Union[TargetAnyOfFirst_andThird, TargetAnyOfSecond_andThird]
```

**Comment by itaru2622** [comment]
hmm, I found this issue is also happened on generating dataclass model, as well besides pydantic model.

command:
```bash
datamodel-codegen --input-file-type jsonschema --output-model-type dataclasses.dataclass --input file.json
```
Results I got: Target model doesn't have inheritance of  First or Second model.

at case1:
```python
from __future__ import annotations
from dataclasses import dataclass

@dataclass
class Target:
    third: str
```

at case2:
```python
from __future__ import annotations
from dataclasses import dataclass

@dataclass
class First:
    first: str
@dataclass
class Second:
    second: str
@dataclass
class Target:
    third: str
```

**Comment by itaru2622** [comment]
@koxudaxi first, thank you for your work about this issue on fix_allOf_anyOf branch as #1291 

I checked your current branch and have some comment.  I will write my comment on your PR post in #1291.
