### ISSUE TITLE
json schema: minus in name results in invalid python module name

### ISSUE THREAD

**Issue by FlorianLudwig** [koxudaxi/datamodel-code-generator#131]
**Describe the bug**
having a `-` inside a definition's name results in an invalid python module name. 

**Expected behavior**

Replace `-` in names with `_`.

**Comment by koxudaxi** [comment]
@FlorianLudwig 
Thank you for creating an issue.

I will fix a bug.

**Comment by koxudaxi** [comment]
@FlorianLudwig 
I have released a fixed version as `0.5.0`
The version converts a module name including `-`  to the snake case name.
Would you please check the version?

**Comment by FlorianLudwig** [comment]
@koxudaxi thanks! works as expected.
