### ISSUE TITLE
Support decimal

### ISSUE THREAD

**Issue by erakli** [koxudaxi/datamodel-code-generator#134]
It would be great to support python's `decimal.Decimal` type.

**Describe the solution you'd like**
There's some [examples](https://github.com/OAI/OpenAPI-Specification/issues/1519#issuecomment-377948881), how it could be implemented on the OpenAPI side:

```
{"type": "string", "format": "decimal"}
{"type": "number", "format": "decimal"}
```

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I understand the feature is WIP in JsonSchema and OpenAPI.
But, I think the feature doesn't break current behavior.
I will implement it.

**Comment by koxudaxi** [comment]
I just relased a new version as `0.5.2`

**Comment by erakli** [comment]
Thank you, it was fast!
