### ISSUE TITLE
Unable to create model from json schema

### ISSUE THREAD

**Issue by priamai** [koxudaxi/datamodel-code-generator#1368]
**Describe the bug**

**To Reproduce**

Example schema: https://schema.ocsf.io/api/1.0.0-rc.3/classes/file_activity?profiles=security_control

Used commandline:
```
datamodel-codegen  --input-file-type jsonschema --url https://schema.ocsf.io/api/1.0.0-rc.3/classes/file_activity?profiles=security_control --output file_activity.py 
```

**Expected behavior**
The model file should be looking like this table: https://schema.ocsf.io/1.0.0-rc.3/classes/file_activity?extensions=

**Version:**
 - OS: Linux
 - Python version: 3.10
 - datamodel-code-generator version: 0.20.0

**Additional context**
Verbose flags produces lots of info.

**Comment by saper** [comment]
Those do not seem to be JSON Schemas as per https://json-schema.org

If you drop `--input-fiile-type jsonschema`, a plain JSON model will be created.

**Comment by saper** [comment]
You can also use their API like this

     curl -X GET "https://schema.ocsf.io/schema/classes/file_activity?profiles=security_control," -H  "accept: application/json"

to get https://json-schema.org Draft 07 file that can be processed with datamodel-code-generator

**Comment by koxudaxi** [comment]
@saper 
Thank you for your answer.
