### ISSUE TITLE
pydantic UserWarning

### ISSUE THREAD

**Issue by kjwpaulson** [koxudaxi/datamodel-code-generator#1412]
**Describe the bug**
```
{redacted part of path}/.venv/lib/python3.11/site-packages/pydantic/main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

**To Reproduce**

Example schema:
[examples/v3.0/petstore.json](https://github.com/OAI/OpenAPI-Specification/blob/9dff244e5708fbe16e768738f4f17cf3fddf4066/examples/v3.0/petstore.json)

Used commandline:
```
from datamodel_code_generator import InputFileType, PythonVersion, generate, DataModelType

# some other code here

generate(
    json_schema,
    output=out_file,
    input_filename=in_file.name,
    input_file_type=InputFileType.OpenAPI,
    output_model_type=DataModelType.PydanticV2BaseModel,
    snake_case_field=True,
    allow_population_by_field_name=True,
    force_optional_for_required_fields=True,  # force-optional
    disable_timestamp=True,
    use_schema_description=True,
    capitalise_enum_members=True,
    use_subclass_enum=True,
    target_python_version=PythonVersion.PY_38,
    validation=True,
    use_double_quotes=True,
    encoding="utf_8",
)
```

**Expected behavior**
No messages

**Version:**
 - OS: `5.15.90.1-microsoft-standard-WSL2`
 - Python version: `Python 3.11.2`
 - datamodel-code-generator version: `0.21.1`
 - pydantic version: `2.0.2`

**Additional context**
At least one other OpenAPISpec json file produced this message (a file I can't share)

**Comment by kjwpaulson** [comment]
Oh, I think this might be a duplicate of https://github.com/pydantic/pydantic/issues/6422 , please close if that's the case.

**Comment by koxudaxi** [comment]
@kjwpaulson 
Thank you for creating the issue.
Yes, I reported the problem to pydantic. But I just remembered that I need to create an issue on this board :sweat_smile:
