### ISSUE TITLE
Invalid code generated for polymorphic array in Swagger spec

### ISSUE THREAD

**Issue by patricksanders** [koxudaxi/datamodel-code-generator#142]
**Describe the bug**
Invalid code generated for polymorphic array in Swagger spec.

**To Reproduce**
Using the following Swagger YAML:
```yaml
openapi: 3.0.0
info:
  title: datamodel-code-generator bug example
components:
  schemas:
    Container:
      allOf:
        - type: object
          required:
            - contents
          properties:
            contents:
              type: array
              items:
                anyOf:
                  - $ref: '#/components/schemas/Type1'
                  - $ref: '#/components/schemas/Type2'
    Type1:
      type: object
      properties:
        prop:
          type: string
    Type2:
      type: object
      properties:
        prop:
          type: string
```

The generated code:
```python
# generated by datamodel-codegen:
#   filename:  swagger-borked.yaml
#   timestamp: 2020-06-10T22:51:26+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Type1(BaseModel):
    prop: Optional[str] = None


class Type2(BaseModel):
    prop: Optional[str] = None


class Container(BaseModel):
    contents: List[Type1, Type2]
```

The last line is invalid and causes a runtime error.
```
TypeError: Too many parameters for typing.List; actual 2, expected 1
```

**Expected behavior**
The generated code should be a list containing a union of the types.
```python
class Container(BaseModel):
    contents: List[Union[Type1, Type2]]
```

This occurs using the latest version of `datamodel-code-generator`, `0.5.2`.

Thanks for the tool! It's very handy. I tried to figure out how to fix this myself but found myself going in circles.

**Comment by FlorianLudwig** [comment]
I believe to properly support this (and all other nested possibilities) some refactoring is needed. Currently only a few cases are handled (see `datamodel-code-generator/datamodel_code_generator/model/base.py` function: `DataModelFieldBase._get_type_hint`).

`DataModelFieldBase.data_types` would need to be converted from a list to a tree, with nodes for `Union`, `List`, etc.

**Comment by koxudaxi** [comment]
@patricksanders 

Thank you for creating this issue.
I will fix the problem. I hope to do this week.

@FlorianLudwig 
Thank you for your good comment.
Yes, We must refactor the method.

> DataModelFieldBase.data_types would need to be converted from a list to a tree, with nodes for Union, List, etc.

I guess We create a new DataType for `List`, `Union`. the new DataType inherits DataType and has DataTypes as children.

**Comment by koxudaxi** [comment]
@patricksanders 
I have fixed and released a new version as `0.5.4`
Would you please check it?

**Comment by patricksanders** [comment]
Wow, that was so fast! My test case looks fixed now. I'll report back if I have any issues, but this looks good to me. Thanks for the quick turnaround.

**Comment by koxudaxi** [comment]
Thank you. I have closed this issue.
Please feel free to report them if you see any problem.
