### ISSUE TITLE
since v0.16.0 `--use-default` is broken when `allOf` is present

### ISSUE THREAD

**Issue by simontaurus** [koxudaxi/datamodel-code-generator#1427]
**Describe the bug**
In v0.15.0 `--use-default` works as expected. Since `v0.16.0`, this is only the case when no `allOf` is present in the schema.

**To Reproduce**

Example schema:
```json
{
    "type": "object",
    "title": "Item",
    "allOf": [{
            "title": "Entity",
            "type": "object"
    }],
    "required": [
        "test",
        "testarray"
    ],
    "properties": {
        "test": {
            "type": "string",
            "default": "test123"
        },
        "testarray": {
            "title": "test array",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "default": [
                "test123"
            ]
        }
    }
}
```

Used commandline:
```
$ datamodel-codegen.exe --input "RequiredWithDefaultTest.json" --input-file-type jsonschema --output "testmodel.py"  --use-default
```

**Expected behavior**
With `v0.15.0` or `allOf` removed from the schema, the result is: 
```python
class Item(BaseModel):
    test: Optional[str] = 'test123'
    testarray: Optional[List[str]] = Field(['test123'], min_items=1, title='test array')
```

**Actual behavior**
With `v0.16.0` and `allOf` present in the schema, the result is: 
```python
class Item(BaseModel):
    test: str
    testarray: List[str] = Field(..., min_items=1, title='test array')
```

**Version:**
 - OS: Windows 10
 - Python version: 3.9.5
 - datamodel-code-generator version: >= v0.16.0

**Additional context**
Is is likely that this is related to #1009 / #1012

**Comment by koxudaxi** [comment]
@simontaurus 
The issue is fixed in the latest version.
Thank you very much!!

**Comment by simontaurus** [comment]
Thank, latest version runs smoothly!
