### ISSUE TITLE
unnecessary = None generated

### ISSUE THREAD

**Issue by FlorianLudwig** [koxudaxi/datamodel-code-generator#143]
**Describe the bug**

I think the tool might generate some `= None` to many, for example here:

https://github.com/koxudaxi/datamodel-code-generator/blob/master/tests/test_main.py#L107

I do have a WIP fix but maybe I am wrong and it should be there?

**Comment by koxudaxi** [comment]
@FlorianLudwig
Yes, you are correct. `Optional` field doesn't need `= None`.
The PR  is welcome!!

**Comment by koxudaxi** [comment]
@FlorianLudwig 

I have released the version as `0.5.22` :tada: 
This feature is added as `--strip-default-none` option.
