### ISSUE TITLE
OpenAPI nested nullable and required components do not generate correct type

### ISSUE THREAD

**Issue by indietyp** [koxudaxi/datamodel-code-generator#1433]
**Describe the bug**

When generating from an OpenAPI spec, when setting `nullable: True` in an object the property is not set to `None` in the model.

(`nullable: boolean` comes from OpenAPI 3.0, I know that in JSONSchema this would be done via `type: ["null"]`)

**To Reproduce**

Example schema:
```json
{
  "openapi": "3.0.3",
  "paths": {
  },
  "components": {
    "schemas": {
      "UnresolvedRightBoundedTemporalInterval": {
        "type": "object",
        "required": [
          "start",
          "end"
        ],
        "properties": {
          "end": {
            "oneOf": [
              {
                "type": "string"
              }
            ],
            "nullable": true
          },
          "start": {
            "oneOf": [
              {
                "type": "string"
              }
            ],
            "nullable": true
          }
        }
      }
    }
  },
  "tags": []
}

```

Used commandline:
```
$ poetry run datamodel-codegen --input-file-type openapi --input 
```

(I use datamodel-codegen to generate pydantic.v2 models, but the problem is the same across versions)

**Expected behavior**

```
# generated by datamodel-codegen:
#   filename:  scratch_37.json
#   timestamp: 2023-07-18T13:13:22+00:00

from __future__ import annotations

from pydantic import BaseModel


class UnresolvedRightBoundedTemporalInterval(BaseModel):
    end: str | None
    start: str | None
```

**Version:**
 - OS: macOS
 - Python version: 3.11
 - datamodel-code-generator version: 0.21.1

**Additional context**

The complete example can be taken from https://github.com/hashintel/hash/blob/6122d21458ebf948f5d5b43c7d3efbfdee01a7f3/apps/hash-graph/openapi/openapi.json#L2320C24-L2335

**Comment by koxudaxi** [comment]
@indietyp 
Thank you for creating the issue.
Can you try `--strict-nullable` option?
The option come from this discussion.
https://github.com/koxudaxi/datamodel-code-generator/issues/327

**Comment by indietyp** [comment]
Although this is not what I would've expected behind `--strict-nullable`
