### ISSUE TITLE
extra_template_data not working

### ISSUE THREAD

**Issue by FlorianLudwig** [koxudaxi/datamodel-code-generator#144]
**Describe the bug**

`custom_template_dir` seems to be ignored:

```python

datamodel_code_generator.generate(custom_template_dir="some/path")

```

**Version:**
 - datamodel-code-generator Version: git master

**Comment by koxudaxi** [comment]
@FlorianLudwig 
Interesting.
It works fine for a simple unittest.
Did you give me some hints? Would you show me custom_template?

**Comment by FlorianLudwig** [comment]
Here a simple way to reproduce this by replacing the `BaseModel.jinja2` without having any effect:

```
mkdir -p template/pydantic
echo "nope" > template/pydantic/BaseModel.jinja2
datamodel-codegen --input datamodel-code-generator/tests/data/openapi/api.yaml --input-file-type openapi --output gen.py --custom-template-dir template
grep nope gen.py
```

**Comment by FlorianLudwig** [comment]
The example I am working with is this one: https://github.com/FlorianLudwig/pdk8s/tree/7e2479ccb1f25c7173368cb0fef2aef7f4501ae9/pdk8s/template

My build process includes copying this folder inside datamodel-code-generator.

**Comment by koxudaxi** [comment]
@FlorianLudwig 
I have understood why the case does not affect results.
```
$ mkdir -p template/pydantic
$ echo "nope" > template/pydantic/BaseModel.jinja2
$ datamodel-codegen --input tests/data/openapi/api.yaml --input-file-type openapi --output gen.py --custom-template-dir template/pydantic
$ grep nope gen.py  |wc -l
6
```
We should specify a nested directory.
But, It may is not correct.
We can't use a custom template for `Enum`.

**Comment by FlorianLudwig** [comment]
oh. okay. I misunderstood how it works then. So not a bug. Closing.

Thanks!

**Comment by koxudaxi** [comment]
@FlorianLudwig 
We should explain the feature in documents.
I have created an issue to add a document for a custom template.
