### ISSUE TITLE
collapse-root-models missing openapi string format type imports

### ISSUE THREAD

**Issue by myke2424** [koxudaxi/datamodel-code-generator#1444]
**Describe the bug**

When models are generated using an input directory of OpenAPI schemas instead of a single openapi.yaml, and the schemas within the directory have references to each other using a file **$ref**, along with the `--collapse-root-models` flag, the generated models file containing the merged collapsed model is **missing imports for its string format type**. This issue is only happening when using an input directory of schemas. 

Based on testing, the bug occurs only when a schema references another schema in a different file, and the referenced schema contains a [string format](https://swagger.io/docs/specification/data-models/data-types/) . Below are screenshots containing the openapi schemas and generated models with missing imports.

**Input schemas directory (schemas/user.yaml, schemas/common.yaml)**
![image](https://github.com/koxudaxi/datamodel-code-generator/assets/21082857/886f2bdd-d1b5-4598-ab6c-72dfbcc12a7b)

**Generated models with missing imports**
![image](https://github.com/koxudaxi/datamodel-code-generator/assets/21082857/1a7d7a1e-72db-4414-a938-3e190ff848d1)

The collapsed root models' attributes, user `id` and `email`, will be of type `UUID` and `EmailStr` in user.py. However, user.py will have missing imports for both UUID and EmailStr. It's using these types but not importing them.

Also, user.py is importing common by doing `from . import common`, but `common.py` does not contain any defined models as they have been collapsed.

**To Reproduce**

1. Create input directory called **schemas**, containing two files, **user.yaml** and **common.yaml** using the schemas below
2. Create output directory called **models**
3. Generate models using the datamodel-codegen command below

**schemas/user.yaml**
```yaml
openapi: 3.0.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          $ref: "common.yaml#/components/schemas/UserId"
        name:
          type: string
        email:
          $ref:  "common.yaml#/components/schemas/email"
```

**schemas/common.yaml**
```yaml
openapi: 3.0.0
components:
  schemas:
    UserId:
      type: string
      format: uuid
    email:
      type: string
      format: email
```

Used commandline:
```
$ datamodel-codegen --input schemas --output models --collapse-root-models
```

**Expected behavior**

In `user.py` the string format types `UUID` and `EmailStr` that are being used should be imported. 

Also, in user.py, the import of `common` is unnecessary since it's not used anywhere in the file. Additionally, there is no need to generate common.py in this scenario since the models from that file were already merged into the User model in user.py.

**expected user.py with string format imports (UUID, EmailStr)**
![image](https://github.com/koxudaxi/datamodel-code-generator/assets/21082857/4277bc22-a975-4931-90c0-452f7bddad5b)

**Version:**
 - OS: Ubuntu 22.04.1 LTS
 - Python version: Python 3.10.6
 - datamodel-code-generator version: 0.21.2

**Comment by koxudaxi** [comment]
`0.24.2` has fixed the issue.
Thank you so much!!
