### ISSUE TITLE
Can we please get a --sorted flag?

### ISSUE THREAD

**Issue by tommyjcarpenter** [koxudaxi/datamodel-code-generator#1480]
Sometimes when I make small changes to our openapi.yaml, and regenerate the pydantic types, massive reshufflings seem to occur, making the diffs appear huge when in fact they are quite small. Can we get a --sorted flag that sorts the types in the pydantic file alphabetically? Thank you!

**Comment by koxudaxi** [comment]
@tommyjcarpenter 
Could you please try the option?
` --keep-model-order    Keep generated models' order`

**Comment by tommyjcarpenter** [comment]
@koxudaxi thank you!! sorry I missed that

**Comment by koxudaxi** [comment]
@tommyjcarpenter 
Thank you for your sponsoring me :smile: 

> (alphabetical sorting would still be nice)

The option is to respect alphabet order as much as possible.
However, it can sometimes be ordered by other dependent classes. (If it's not a bug.)
