### ISSUE TITLE
Graph Api

### ISSUE THREAD

**Issue by aersam** [koxudaxi/datamodel-code-generator#1512]
**Describe the bug**
Yes, that's probably a very hard one, but I tried generating model out of Microsoft's Open Api Spec for their Graph API - 29 MB of a definition file ;) 

It generates a number of warnings and does not generate most models. I was interestend in "microsoft.graph.event" which was not there. Also I get a number of warnings:

```
.venv\lib\site-packages\pydantic\main.py:309: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
.venv\lib\site-packages\datamodel_code_generator\parser\jsonschema.py:339: UserWarning: format of 'base64url' not understood for 'string' - using default
  warn(
.venv\lib\site-packages\datamodel_code_generator\parser\jsonschema.py:339: UserWarning: format of 'duration' not understood for 
'string' - using default
  warn(
.venv\lib\site-packages\datamodel_code_generator\parser\jsonschema.py:339: UserWarning: format of 'int16' not understood for 'integer' - using default
  warn(
.venv\lib\site-packages\datamodel_code_generator\parser\jsonschema.py:339: UserWarning: format of 'uint8' not understood for 'integer' - using default
  warn(
```

**To Reproduce**
You can find it here: https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml

Used commandline:
```
$ datamodel-codegen --input .\graphapi_openapi.yaml --output model --input-file-type openapi --output-model-type "pydantic_v2.BaseModel" --openapi-scopes schemas
```

**Expected behavior**
well it should generate my models ;) 

**Version:**
 - OS: Windows
 - Python version: 3.11
 - datamodel-code-generator version: 0.21.4

**Additional context**
I do have pydantic 2.3 installed

**Comment by koxudaxi** [comment]
@aersam 
I'm sorry for my late reply.
I tried to generate the model from the schema.
I can see the Event model.
Could you please re-try it with the latest version?
![image](https://github.com/koxudaxi/datamodel-code-generator/assets/630670/3b99e4c2-6700-44bf-8a1c-d193e4a39ffa)
