### ISSUE TITLE
Alphabetize options in help output

### ISSUE THREAD

**Issue by howardj99** [koxudaxi/datamodel-code-generator#1539]
**Is your feature request related to a problem? Please describe.**
With the number of options growing, it’s becoming more difficult to find help text for a particular named CLI option. 

**Describe the solution you'd like**
Either manually sort the argparse declarations or use a custom help formatter ([example]( https://stackoverflow.com/a/12269143)).

**Describe alternatives you've considered**
Adding [groups](https://docs.python.org/3/library/argparse.html#argument-groups) to organize options by their purpose.

**Additional context**

**Comment by koxudaxi** [comment]
The PR had been released as `0.22.0`
Thank you very much!!
