### ISSUE TITLE
Issue with generating model from JSON Compound Schema

### ISSUE THREAD

**Issue by clementboutaric2** [koxudaxi/datamodel-code-generator#1541]
**Describe the bug**

Trying to generate a pydantic model from a compound JSON schema fails and returns following error (just the end of the otherwise very long message) :  
`yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 11, column 25`

**To Reproduce**

Taken from [json-schema doc](https://json-schema.org/understanding-json-schema/structuring.html)

Example schema:
```json
{
  "$id": "https://example.com/schemas/customer",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "first_name": { "type": "string" },
    "last_name": { "type": "string" },
    "shipping_address": { "$ref": "/schemas/address" },
    "billing_address": { "$ref": "/schemas/address" }
  },
  "required": ["first_name", "last_name", "shipping_address", "billing_address"],

  "$defs": {
    "address": {
      "$id": "/schemas/address",
      "$schema": "http://json-schema.org/draft-07/schema#",

      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "$ref": "#/definitions/state" }
      },
      "required": ["street_address", "city", "state"],

      "definitions": {
        "state": { "enum": ["CA", "NY", "... etc ..."] }
      }
    }
  }
}
```

Used commandline:
```
$ datamodel-codegen  --input .\json_schema\test.json --input-file-type jsonschema --output test.py
```

**Expected behavior**
Expected the generation of a pydantic schema

**Version:**
 - OS: windows 11 22H2
 - Python version: 3.11.4
 - datamodel-code-generator version: 0.21.4

**Additional context**
Similar issue was described in jsonschema $ref parsed as yaml? #564, however I tried to replace the base URI with "blank" and now I got FileNotFound error when refering to the sub $id

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
the current version doesn't support `$defs`
We should support it.
https://github.com/koxudaxi/datamodel-code-generator/issues/1578

**Comment by koxudaxi** [comment]
@clementboutaric2 
the latest version supports `$defs`.
I close this issue. thank you
