### ISSUE TITLE
Missing import for Field

### ISSUE THREAD

**Issue by FlorianLudwig** [koxudaxi/datamodel-code-generator#157]
**Describe the bug**

**To Reproduce**

Example schema:
example file `https://raw.githubusercontent.com/kubernetes/kubernetes/1.16.4/api/openapi-spec/swagger.json`

Generated code in `io/k8s/apimachinery/pkg/version.py`:
```
from __future__ import annotations

from pydantic import BaseModel


class Info(BaseModel):
    build_date: str = Field(..., alias="buildDate")
    compiler: str
    git_commit: str = Field(..., alias="gitCommit")
    git_tree_state: str = Field(..., alias="gitTreeState")
    git_version: str = Field(..., alias="gitVersion")
    go_version: str = Field(..., alias="goVersion")
    major: str
    minor: str
    platform: str
```

**Expected behavior**

`from pydantic import BaseModel, Field`

**Version:**
 - OS: Linux
 - Python Verison: 3.8
 - datamodel-code-generator master

**Comment by FlorianLudwig** [comment]
@koxudaxi it might be an interesting integration test to run datamodel-code-generator on a complex definition like the kubernetes one and then run mypy on the resulting code - it brings up several issues :)

**Comment by koxudaxi** [comment]
> it might be an interesting integration test to run datamodel-code-generator on a complex definition like the kubernetes one and then run mypy on the resulting code - it brings up several issues :)

@FlorianLudwig 
Interesting. I want the test to use our product :smile: 

OK, I will fix it.

I have some issues.  I start it by fixing easy matters.

**Comment by koxudaxi** [comment]
@FlorianLudwig 
I run the code-generator with the swagger.json
the result doesn't have fields.
Why did you get the code which has Field for an alias?
I'm confused.

`io/k8s/apimachinery/pkg/version.py`

```python
# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2020-06-20T17:18:25+00:00

from __future__ import annotations

from pydantic import BaseModel


class Info(BaseModel):
    buildDate: str
    compiler: str
    gitCommit: str
    gitTreeState: str
    gitVersion: str
    goVersion: str
    major: str
    minor: str
    platform: str

```

**Comment by FlorianLudwig** [comment]
Hey @koxudaxi,

I am sorry. This isn't and issue with your code but with mine!  I have a custom parser that adds aliases. 

Closing this.

**Comment by koxudaxi** [comment]
`snake_case` field option is very good idea.
I want the feature.

**Comment by FlorianLudwig** [comment]
I have a function I run over all fields:

`snakify_field`: https://github.com/FlorianLudwig/pdk8s/blob/master/pdk8s/gen_k8s.py#L59 - but it's buggy as noticed in this report :sweat:
