### ISSUE TITLE
Enum is not considered for default value

### ISSUE THREAD

**Issue by twwd** [koxudaxi/datamodel-code-generator#1616]
**Describe the bug**

For a property of type enum, the default value is not resolved correctly. It is set to a string instead of the enum  identifier.

**To Reproduce**

Example schema:
```yaml
openapi: 3.0.3
info:
  title: Bug report
  version: 0.0.1
paths:
  /api:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: ''
components:
  schemas:
    Model:
      type: object
      properties:
        notification:
          enum:
            - slack
            - msteams
            - mail
            - alert
          type: string
          default: alert
```

Used commandline:
```
$ datamodel-codegen --input openapi.yaml --output models.py --input-file-type openapi
$ datamodel-codegen --input openapi.yaml --output models.py  --output-model-type dataclasses.dataclass --input-file-type openapi
```

**Expected behavior**

Models has property ` notification: Optional[Notification] = Notification.alert` instead of `notification: Optional[Notification] = 'alert'.

**Version:**
 - OS: Windows
 - Python version: 3.10
 - datamodel-code-generator version: 0.22.1

**Comment by koxudaxi** [comment]
@twwd 
You can use ` --set-default-enum-member` to set Enum member as default.
```
  --set-default-enum-member
                        Set enum members as default values for enum field

```

**Comment by twwd** [comment]
Sorry, I overlooked the option. Wouldn't that make sense as default, otherwise it creates invalid code?

**Comment by koxudaxi** [comment]
@twwd 
You are right. I expect the use case in pydantic. It will be cast to enum.
But, dataclass doesn't change the default value to an enum.
we should enable the option by default in dataclass.
