### ISSUE TITLE
Default list value is not mapped to default_factory for dataclasses.field

### ISSUE THREAD

**Issue by twwd** [koxudaxi/datamodel-code-generator#1617]
**Describe the bug**
For a property of type array with a default value, the default value is directly set to a list which is therefore mutable.

**To Reproduce**

Example schema:
```yaml
openapi: 3.0.3
info:
  title: Bug report
  version: 0.0.1
paths:
  /api:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: ''
components:
  schemas:
    Model:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
          default:
            - default-tag
```

Used commandline:
```
$ datamodel-codegen --input openapi.yaml --output models.py  --output-model-type dataclasses.dataclass --input-file-type openapi
```

**Expected behavior**

I expect that the property is mapped to `tags: list[str] | None = field(default_factory=lambda: ['default-tag'])` instead of `tags: list[str] | None = ['default-tag']`.

**Version:**
 - OS: Windows
 - Python version: 3.10
 - datamodel-code-generator version: 0.22.1

**Comment by koxudaxi** [comment]
The issue is fixed in the latest version.
Thank you very much!!
