### ISSUE TITLE
JSON-Schemas: Better namespacing options regarding `--reuse-model`

### ISSUE THREAD

**Issue by lord-haffi** [koxudaxi/datamodel-code-generator#1631]
Hi, I couldn't figure out a way to do it nicely so I just wanted to ask if I'm missing something..

I have various JSON-Schemas which are referencing each other e.g.
```
- src
    - pkg1
        - A.json
        - B.json
    - pkg2
        - C.json
```
and something like
```json
{
    "additionalProperties": true,
    "description": "Some class description",
    "properties": {
        "bRef": {
            "anyOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/[owner]/[repo]/main/src/pkg1/B.json#"
                },
                {
                    "type": "null"
                }
            ],
            "default": null,
            "title": "bRef"
        },
        "cRef": {
            "anyOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/[owner]/[repo]/main/src/pkg2/C.json#"
                },
                {
                    "type": "null"
                }
            ],
            "default": null,
            "title": "bRef"
        },
    },
    "title": "A",
    "type": "object"
}
```

Putting this schema into the generator creates one file with all the models inside it. But I would rather like to recreate the same structure and import the models from the other files instead. Something like:

```
- src
    - pkg1
        - A.py
        - B.py
    - pkg2
        - C.py
```
and
```python
from pkg1.B import B
from pkg2.C import C

class A(BaseModel):
    """Some class description"""
    bRef: B | None = None
    cRef: C | None = None
```

The option `--reuse-model` is not exactly what I want because it would need the schemas defined in `$defs` with special scopes in the names. It seems like the namespace is created by using the part after the `#` sign - right? Is there maybe something like a `base-path` which would enable parts of the URI to count into the namespace as well or something similar?

If not, could you give me a good place to start with? I'm currently debugging through the parsing methods but I'm having a hard time to get around the `ModelResolver` (I tried to simply remove the models from the result list but the resolver complains about unresolved references - which is absolutely correct of course). But maybe this is the wrong place to do the trick, do you have any suggestions?

**Comment by lord-haffi** [comment]
Hey, me again. I finally got it to work for by using a customized data model type and overwriting the `module_path` and `module_name` property. Though, it might be interesting to have such a feature so I will leave this open for now.

**Comment by koxudaxi** [comment]
@lord-haffi 
I'm sorry for my late reply.


we can set the directory as input 
```bash
datamodel-codegen --input src --output output
```

input
```
- src
    - pkg1
        - A.json
        - B.json
    - pkg2
        - C.json
```
output
```
- output
    - pkg1
        - __init__.py 
        - A.py
        - B.py
    - pkg2
        - __init__.py
        - C.py
```

A.py
```python
# generated by datamodel-codegen:
#   filename:  pkg1/A.json
#   timestamp: 2023-11-08T16:06:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra, Field

from ..pkg2 import C
from . import B


class A(BaseModel):
    class Config:
        extra = Extra.allow

    bRef: Optional[B] = Field(None, title='bRef')
    cRef: Optional[C] = Field(None, title='bRef')


A.update_forward_refs()

```

If a model is doing circular references, etc., you may not be able to generate a complete Python module.
We hope to resolve this in the future, but currently, there is a problem with some complex schemas that need to generate proper Python files.

https://github.com/koxudaxi/datamodel-code-generator/issues/836

**Comment by lord-haffi** [comment]
Well, don't know why I didn't think of that. Thanks a lot, this helped to improve my code 👍
