### ISSUE TITLE
Use UPPER_CASE for enum options names

### ISSUE THREAD

**Issue by ADR-007** [koxudaxi/datamodel-code-generator#1673]
Enum options are constants, so they should be in UPPER_CASE but currently it is as value

New parameter --enum-names-in-upper-case can be added to automatically convert names to UPPER_CASE

Expected:
```py
class MyStatus(str, Enum):
    PENDING = 'pending'
    RUNNING = 'running'
    SUCCESS = 'success'
    ERROR = 'error'
```

Actual:
```py
class MyStatus(str, Enum):
    pending = 'pending'
    running = 'running'
    success = 'success'
    error = 'error'
```

**Comment by santhoshramaraj** [comment]
Under the hood, the generate method already has an option `capitalise_enum_members` that does this but has to be exposed to the CLI

**Comment by koxudaxi** [comment]
@ADR-007 @santhoshramaraj 
Sorry, I forgot the option.
```
  --capitalise-enum-members, --capitalize-enum-members
                        Capitalize field names on enum
```


https://github.com/koxudaxi/datamodel-code-generator/blob/c63b87e5f616b0df21df23b83f89a56e587b6416/tests/data/expected/main/main_json_capitalise_enum_members/output.py#L10-L14

**Comment by ADR-007** [comment]
Thank you!
