### ISSUE TITLE
Recursive elements results in wrong model

### ISSUE THREAD

**Issue by fzirker** [koxudaxi/datamodel-code-generator#168]
I am generating models from JSON Data which comes from an external source.  In my JSON file there is a element which contains a other sub element with the same name. 

Example JSON
```json
{
    "recursive": {
        "sub": {
            "recursive": {
                "value": 42.23
            }
        }
    }
}
```

Used commandline:
```
$ datamodel-codegen --input jsons/recursive.json --input-file-type json --output models/recursive.py --target-python-version 3.6
```

**Expected behavior**
The Model should look like this.
```python
class Recursive(BaseModel):
    sub: 'Sub'

class Recursive2(BaseModel):
    sub: float

class Sub(BaseModel):
    recursive: 'Recursive2'

class Model(BaseModel):
    recursive: 'Recursive'
```

But it looks like this and has an indirect recursion in `Recursive`->`Sub`->`Recursive`...  :
```python
class Recursive(BaseModel):
    sub: 'Sub'

class Sub(BaseModel):
    recursive: 'Recursive'

class Model(BaseModel):
    recursive: 'Recursive'
```
**Version:**
 - OS: Ubuntu 20.04
 - Python Verison: 3.6
 - datamodel-code-generator Version 0.5.13

**Comment by koxudaxi** [comment]
@fzirker 
OK, I have understood it.
We have to check the contents of models to compare same name models,
I will fix it.

**Comment by koxudaxi** [comment]
@fzirker 
In version `0.5.16`, this problem is resolved :tada: 

https://github.com/koxudaxi/datamodel-code-generator/pull/177/files
