### ISSUE TITLE
How to use json_schema_extra for pydantic_v2.BaseModel

### ISSUE THREAD

**Issue by zhangbc97** [koxudaxi/datamodel-code-generator#1680]
Pydantic V2 deprecated **extra for Field

https://docs.pydantic.dev/2.4/migration/#changes-to-pydanticfield

How to generate code with json_schema_extra when enable  `--field-include-all-keys`

**Comment by gjcarneiro** [comment]
I get this warning:

pydantic.warnings.PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example').

**Comment by gjcarneiro** [comment]
Note: my problem with `example` was fixed by #1705.

**Comment by koxudaxi** [comment]
I'm sorry for the late reply.
OK, we should move the extra keys to json_schema_extra as dict.
