### ISSUE TITLE
sqlmodel.SQLModel support

### ISSUE THREAD

**Issue by iridescentGray** [koxudaxi/datamodel-code-generator#1799]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
output-model-type  support   https://github.com/tiangolo/sqlmodel

**Describe alternatives you've considered**
Use Custom Templates

**Additional context**
Thank you for all you do.

**Comment by iridescentGray** [comment]
oh, i use the following command  implemented basic support
* datamodel-codegen  --input test_json_data.json --input-file-type json --base-class t  --base-class sqlmodel.SQLModel  --output test_json_data_model.py

**Comment by meicale** [comment]
This can generate the code BUT, this is not a functional model that can interact with a real database, at least it need set `table = true` in the class defination. 
Would you mind reopen it? It is a great feather needed!

**Comment by meicale** [comment]
> This can generate the code BUT, this is not a functional model that can interact with a real database, at least it need set `table = true` in the class defination.
> Would you mind reopen it? It is a great feather needed!

This can generate the code BUT, this is not a functional model that can interact with a real database, at least it need set table = true in the class defination. IMO, supporting sqlmodel seems hard than you think!
Would you mind reopen it? It is a great feather needed!
