### ISSUE TITLE
create pydantic model class from schema

### ISSUE THREAD

**Issue by shaojun** [koxudaxi/datamodel-code-generator#1865]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
create a model class (`type[BaseModel]`) by schema

**Describe alternatives you've considered**

**Additional context**
I see there's `create_model` function that allow pass in json string and get a model class (`type[BaseModel]`), like:
```
from pydantic import BaseModel, create_model
pydantic_model_type = create_model(
            'model_from_air', '{"name":"foo", "age":99}')
```

**Comment by koxudaxi** [comment]
also, the comment may help you.
https://github.com/koxudaxi/datamodel-code-generator/issues/278#issuecomment-764498857
