### ISSUE TITLE
CLI options `use-standard-collections` and `use-union-operator` are not being applied for input file type `graphql`

### ISSUE THREAD

**Issue by paultop6** [koxudaxi/datamodel-code-generator#1941]
**Describe the bug**
CLI options `use-standard-collections` and `use-union-operator` are not being applied for input file type `graphql`

**To Reproduce**

Example schema:
```graphql

 type DummyType {
    id: ID!
    label: String!
    value: Int
}

type DummyType2 {
    list_types: [DummyType]
}

```

Used commandline:
```
$ datamodel-codegen --input test.graphql --input-file-type=graphql --output-model-type pydantic_v2.BaseModel --use-standard-collections --use-union-operator --output test_models.py
```

**Expected behavior**
`Optional` should be replaced by union operator `|`, e.g. `Optional[str]` should be replaced by `str | None`.  `List` should be replaced by standard type `list`

**Version:**
 - OS: MAC OS Sonoma 14.4.1
 - Python version: 3.11.9
 - datamodel-code-generator version: 0.25.6

**Additional context**

**Comment by paultop6** [comment]
I have also noticed the same behaviour with option `--use-default-kwarg`

**Comment by bpsoos** [comment]
hello @paultop6 I have published a PR that should fix the --use-standard-collections --use-union-operator --use-annotated options for graphql input file type
