### ISSUE TITLE
Remove linters from package dependency

### ISSUE THREAD

**Issue by PythonFZ** [koxudaxi/datamodel-code-generator#2010]
Would it be possible to move the code formatting tools to a dedicated poetry group such as `[tool.poetry.group.dev.dependencies]` or are they required for the package to work?

https://github.com/koxudaxi/datamodel-code-generator/blob/28be37d7c2a0b0bce21b0719ffb732df36ebce74/pyproject.toml#L54-L55

**Comment by koxudaxi** [comment]
Required.

The generated code is formatted using these linter at the end of the code generation.
