### ISSUE TITLE
Pass through example strings

### ISSUE THREAD

**Issue by languitar** [koxudaxi/datamodel-code-generator#206]
**Is your feature request related to a problem? Please describe.**

As a validation step for using this tool I have taken an existing API built with fastapi and pydantic models and applied the code generator on the openapi specification provided by openapi. In the generated models the example is missing. As we want to take parts of the generated models also as output models again, it would be nice if those examples could also be passed into the pydantic models.

**Describe the solution you'd like**

In case the openapi specification contains a custom `example` for a field, pass this example to the `example` argument of the pydantic `Field`.

**Describe alternatives you've considered**

I don't see an alternative.

**Comment by koxudaxi** [comment]
@languitar 
Thank you for requesting a feature.
It's good.
I will implement it.

**Comment by koxudaxi** [comment]
@languitar 
I implemented it.
I have released a new version as `0.5.30`

**Comment by languitar** [comment]
Thanks! that was quick!
