### ISSUE TITLE
Option to disable timestamp

### ISSUE THREAD

**Issue by languitar** [koxudaxi/datamodel-code-generator#217]
**Is your feature request related to a problem? Please describe.**
 
Please add an option to disable the timestamp comment in generated files. This conflicts with the idea of reproducible builds: https://reproducible-builds.org/docs/timestamps/. Given the same specification the same output should be generated.

**Describe the solution you'd like**

An additional command line switch would be ok for us.

**Describe alternatives you've considered**

I don't see many alternatives that are not a brittle hack.

**Comment by koxudaxi** [comment]
Thank you for your suggestion.
I agree with your thought.
I will add the option.

**Comment by koxudaxi** [comment]
@languitar 
I have released a new version as `0.5.33` :tada:

**Comment by languitar** [comment]
Thanks, works as expected
