### ISSUE TITLE
GitHub About section doesn't reflect full capabilities

### ISSUE THREAD

**Issue by JosXa** [koxudaxi/datamodel-code-generator#222]
![image](https://user-images.githubusercontent.com/7313176/93808665-9540fe00-fc4c-11ea-9446-24ee82179352.png)

Looks like the GH "About" section could use some more spice (and typo fixes) for how awesome this library is. How about 
```
Pydantic model generator for easy conversion of JSON, OpenAPI, JSON Schema, and YAML data sources.
```
? 🚀 
Not sure if one can link to each of these entities aswell... Here are the links:
- https://pydantic-docs.helpmanual.io/
- https://json-schema.org/

**Comment by koxudaxi** [comment]
@JosXa 
Thank you for creating this issue.

I have changed it. :writing_hand: 
Also, I can not insert a hyperlink in `About`  :cry: 

![Screenshot_2020-09-22_04-17-32](https://user-images.githubusercontent.com/630670/93811374-03a4b100-fc8b-11ea-8bda-5d1b5ac980df.png)

**Comment by JosXa** [comment]
@koxudaxi Sweet :)
