### ISSUE TITLE
Unexpected behavior for use_default

### ISSUE THREAD

**Issue by JosXa** [koxudaxi/datamodel-code-generator#242]
On 0.6.0, I'm trying to use the new `use_default_value_for_required_field` argument.

**Expectation:**

All fields will have a default value, no matter if they're required or not.

**Actual:**

![image](https://user-images.githubusercontent.com/7313176/96939080-4c3ecc80-14cc-11eb-8ba4-dbbf4f1d1809.png)
Not all fields have a default.

I'm wondering if this was meant to be an `or`:
https://github.com/koxudaxi/datamodel-code-generator/blob/dbd146a26e0000d2670bc0a79fa6d73b1b5d490d/datamodel_code_generator/parser/jsonschema.py#L400

**Comment by koxudaxi** [comment]
@JosXa 
I'm sorry too late.
I guess you are right. :+1: 
I will fix it.
Thank you.

**Comment by koxudaxi** [comment]
@JosXa 
I re-checked the problem.
But, I think the current implementation does not expect your case.
This option is for a field that has a default value.

I think you are expecting all fields.
If you want to change all fields to optional fields, then we need another option.

**Comment by JosXa** [comment]
Then the naming is kind of misleading, hmmm.. what is it supposed to do exactly?

**Comment by koxudaxi** [comment]
@JosXa 
I expect the behavior.
How did you think about it?
| use_default_value_for_required_field | default value | required |  result | 
| -------------  | ------------- | ------------- | ------------- |
| false | 100 | true  | name :int | 
| false | 100 | false | name: Optional[int] = 100 |
| true | 100 | true | name: int = 100 |
| true | - | true | name: int |

**Comment by JosXa** [comment]
Aah, okay I see now. Two remarks:

1. Let me just make some suggestions from the top of my head for a maybe clearer name:
- `ignore_defaults_for_required_fields` (inverted)
- `apply_required_field_defaults` (or `apply_default_values_for_required_fields` but that's long)

2. Okay so what I was looking for is basically a `use_optional_for_required_fields` or `force_optional_for_required_fields`. The reason is that I would like to avoid all runtime errors when data comes from an external API and only validate field types if they're present. This is useful for prototyping and I'd rather like to start with `Optional` fields and later make them non-optional when I know which fields my application is really going to rely on. In some cases the library also generates non-optional fields even when sometimes the values are None. I'll give you an example the next time I encounter this :)

**Comment by koxudaxi** [comment]
I prefer `ignore_defaults_for_required_fields` :)
I will change the name of the attribute.

I have understood what you want when I read about 2.
Also about this, I implement.

Thank you for your great suggestion.

**Comment by koxudaxi** [comment]
@JosXa 
I have released a new version as `0.6.2`
This release includes two changes.
1. change attribute name. `use_default_on_required_field` to `apply_default_values_for_required_fields`
2. add `--force-optional` to `enable force_optional_for_required_fields`
