### ISSUE TITLE
Generation of models from the Python dictionary

### ISSUE THREAD

**Issue by DjaPy** [koxudaxi/datamodel-code-generator#246]
Thank you for the nice package. It is possible to generate models from dict python objects

At the input, I have a python file in which a variable is declared and a dictionary is passed to it. At the output, you need to get a file with the model name as a variable.

The path from the dictionary to the json schema and then to the model is complex. Has an extra step.

Example.

input:
```python
example_variable = {"test_field": "test_value", "test_field2" : 123}
```
output:
```python
class ExampleVariable(BaseModel):
    "test_field": str
    "test_field2" : int
```

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I think your idea is useful.

Did you want to use the feature as a CLI or a module?
Currently, this module supports parsing Jsom object to Pydantic models.
The feature can be used for your use-case. of course, we should rethink the interface of the module.

**Comment by DjaPy** [comment]
I would be interested in two types of implementation.
Can I help? Maybe you can show me what to start from and I will do PR?

**Comment by koxudaxi** [comment]
Of course, PR welcome.
 I show you an approach to add the feature in the module.

This enum is used as the CLI option to detect file type in `generate()`.
We should add a new type.
https://github.com/koxudaxi/datamodel-code-generator/blob/bddf61aaaf98602530dde68028f6f5f4b77ee749/datamodel_code_generator/__init__.py#L99-L104

This code converts Json, Yaml data to JSONSchema with [genson](https://github.com/wolverdude/genson/).
I think we can use the same way for `dict`.
https://github.com/koxudaxi/datamodel-code-generator/blob/bddf61aaaf98602530dde68028f6f5f4b77ee749/datamodel_code_generator/__init__.py#L168-L185


Also, there is a guide for contribution.
https://koxudaxi.github.io/datamodel-code-generator/development-contributing/

**Comment by koxudaxi** [comment]
@DjaPy 
I implemented the feature. And I have released a new version as `0.6.20`.
The feature accepts only python dictionary include list.
A lot of users will prefer this simple way.

Thank you very much.

## Example
### data.py
```python
{'test_field': 'test_value', 'test_field2': 123, 'test_fields3': [1, 2, 3]}
```

### Command
```bash
$ datamodel-codegen --input data.py --input-file-type dict
```

### Output
```python
# generated by datamodel-codegen:
#   filename:  data.py
#   timestamp: 2021-01-15T17:12:25+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    test_field: str
    test_field2: int
    test_fields3: List[int]

```

**Comment by DjaPy** [comment]
Excellent. Thank you

**Comment by benlawraus** [comment]
Is it possible to turn the above output to

```
class Model(BaseModel):
    test_field: str = 'test_value'
    test_field2: int = 123
    test_fields3: List[int] = [1,2,3]
```

Thanks for your time!
