### ISSUE TITLE
make a conda-forge package

### ISSUE THREAD

**Issue by Chilipp** [koxudaxi/datamodel-code-generator#252]
Hey @koxudaxi!

Would you be interested to make this package available via the [conda-forge](https://conda-forge.org) anaconda channel?
In case there is interest, I'd be happy to draft a PR for the [staged-recipes](https://github.com/conda-forge/staged-recipes) repository.

I strongly recommend anaconda. Particularly for Python it has a lot of very convenient functionalities and makes the installation of c, c++ and FORTRAN-based packages much more convenient on all platforms (see this blog post for instance: https://www.anaconda.com/blog/understanding-conda-and-pip). The conda-forge channel is community-driven platform with the basic idea that the maintainers of the packages make their packages available via conda. The overhead of maintaining a package like `datamodel-code-generator` is very low. Each package in this channel get's a dedicated github repository (see [this one for pydantic](https://github.com/conda-forge/pydantic-feedstock), for instance). Everytime a new release is made on pypi, a bot will create a PR to also update the package on the conda-forge channel (see [here](https://github.com/conda-forge/pydantic-feedstock/pull/46) for instance) and, once it is merged, it makes the package available via `conda install -c conda-forge docstring_parser`

Anyway, for a package like `datamodel-code-generator` it of course does not make many advantages, as the installation via `pip` is straight-forward, but for more complex packages that might depend on it in the future, conda gives a great benefit and therefore it would be good to have it available there, too.

Are you ok if I add you there as a maintainer? I can take care of it, if you like (it's [anyway not much work](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role)), but as the creator of this package, you should have access to the Github repository, too.

**Comment by koxudaxi** [comment]
@Chilipp 
Thank you for your suggestion.
I want to push this package to conda-forge.
What should I do it?

**Comment by koxudaxi** [comment]
@Chilipp 
Did you have any updates?
I need your help.

Thank you

**Comment by Chilipp** [comment]
hey @koxudaxi, my apologies for being so silent. You just have to prepare a PR for the staged-recipes repository with your recipe (see [the docs](https://github.com/conda-forge/staged-recipes#getting-started)). You can do it yourself if you like, or I prepare a recipe, make the PR and list you there as a maintainer.

**Comment by koxudaxi** [comment]
@Chilipp 
Thank you for your explanation.
I will read the document and make a PR when I get the time.
Also, your PR welcome. But, I know you are busy too :wink:

**Comment by koxudaxi** [comment]
We can download `datamodel-code-generator` from conda-forge.
https://github.com/conda-forge/staged-recipes/pull/22022
https://anaconda.org/conda-forge/datamodel-code-generator
