### ISSUE TITLE
"A Parser can not resolve classes" for modular json schema structure

### ISSUE THREAD

**Issue by themmes** [koxudaxi/datamodel-code-generator#267]
**Describe the bug**

The parser cannot resolve all classes for a modular json schema structure

`Exception: A Parser can not resolve classes: [class: Person references: {'pet.JsonPet'}].`

**To Reproduce**

Example schema:
```
/schema
  person.json
  /definitions
    pet.json
```

```json
{
  "$id": "person.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "first_name": {
      "type": "string",
      "description": "The person's first name."
    },
    "last_name": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years.",
      "type": "integer",
      "minimum": 0
    },
    "pets": {
      "type": "array",
      "items": [
        {
          "$ref": "definitions/pet.json#Pet"
        }
      ]
    },
    "comment": {
      "type": "null"
    }
  },
  "required": [
      "first_name",
      "last_name"
  ],
}
```

```json
{
  "$id": "pet.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Pet",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    }
  }
}
```

Used commandline:
```
$ datamodel-codegen --input schema --input-file-type jsonschema --output test.py
```

**Expected behavior**
I expected similar output as described in https://pydantic-docs.helpmanual.io/datamodel_code_generator

**Version:**
 - OS: macOS Catalina 10.15.4 (19E287)
 - Python version: Python 3.8
 - datamodel-code-generator version: datamodel-codegen --version
0.6.2

**Additional context**
Maybe I'm structuring the refs incorrectly, I would love to know how to change them to make this work. Thanks in advance!

**Comment by themmes** [comment]
Duplicate of https://github.com/koxudaxi/datamodel-code-generator/issues/215

**Comment by themmes** [comment]
The problem was a mistake in my example, the reference should be `"$ref": "definitions/pet.json#/Pet"` and then it works perfectly!

**Comment by koxudaxi** [comment]
I'm sorry for the late reply.
Yes, `#` needs `/`

**Comment by themmes** [comment]
Are you kidding? I listed this yesterday, please don't feel rushed by my comments. You're doing an amazing job on this library! 👍

**Comment by koxudaxi** [comment]
Thank you for your comment.
I want to reply as soon as possible :)
