### ISSUE TITLE
Support String Formats

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/datamodel-code-generator#30]
## Format types
- [x] date 
- [x] date-time 
- [x] password 
- [ ] byte
- [x] binary 
- [x] email
- [x] uuid
- [x] uri
- [x] hostname
- [x] ipv4
- [x] ipv6
- [x] deciaml

**Comment by shalseban** [comment]
Is this issue closed?

**Comment by koxudaxi** [comment]
@shalseban 
Good question.
`byte` is not implemented. 

OpenAPI expects that byte is base64-encoded characters.
https://swagger.io/docs/specification/data-models/data-types/#string

But, I don't know how do we treat encoded/decoded values like base64 in Pydantic.
I opened this issue. However, the problem is not resolved yet. 
https://github.com/samuelcolvin/pydantic/issues/692

**Comment by shalseban** [comment]
@koxudaxi Thanks for the response. 

Does it make sense to release with the other formats and open another issue for `byte` support?

If not, is there a work around in the meantime?

**Comment by koxudaxi** [comment]
You are right.
I have close this issue. 
And I will create a new issue for only `byte`.

**Comment by koxudaxi** [comment]
@shalseban 
I have opened a new issue for `byte`.

Thank you very much :smile:
