### ISSUE TITLE
Dynamic creation of BaseModel classes at runtime

### ISSUE THREAD

**Issue by makkus** [koxudaxi/datamodel-code-generator#331]
**Is your feature request related to a problem? Please describe.**

I want to dynamically create classes that inherit from BaseModel (and later objects from those classes) at runtime, and use them in the same process. I could use the rendered files and load those dynamically, but that seems like a roundabout way of doing it.

**Describe the solution you'd like**

I am not sure if that would be enough, but ideally I'd like this library to be split up into 2 components, conceptually: 

- generating a generic, internal schema with the necessary field names, type information, and other metadata
- rendering this schema in different ways (maybe via plugins)

The first part is already implemented here, as far as I see. But it is tightly coupled with the rendering of Python files that contain the BaseModel child classes source code. 

I would like to be able to intercept this, and 'render' that structure differently. The most important case would be to generate a Python class dynamically (which should be relatively easy, using ``type(...)``. Another use-case (although less important) would be to 'translate' the schema into a different format (I would have a use for Avro, for example). Basically, ``datamodel-code-generator`` could become sort of an any-to-any schema translator. I know this is not the original goal of this project, and I could totally understand how that is way out of scope, but I have come across a need for something like this a few times in the past.

**Describe alternatives you've considered**

I have considered to implement this myself before from scratch, but haven't had the time yet. I also only just now discovered ``datamodel-code-generator``, and it looks to me that there is quite a bit of code that could be re-used for my purpose. So one alternative would be to start a new library using a good chunk of what's available here.

**Comment by koxudaxi** [comment]
@makkus 
Thank you for creating this issue.

> I want to dynamically create classes that inherit from BaseModel (and later objects from those classes) at runtime, and use them in the same process. I could use the rendered files and load those dynamically, but that seems like a roundabout way of doing it.

I know that some users want the feature.
There is a workaround on this page. You may have already checked it.
https://koxudaxi.github.io/datamodel-code-generator/using_as_module/


> I would like to be able to intercept this, and 'render' that structure differently. The most important case would be to generate a Python class dynamically (which should be relatively easy, using type(...). 

I have not written an example to generate a Python class dynamically without writing models in files.

But, We can do it easily by using  [Parser.parse()](https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/__init__.py#L291) that gets a dict that includes generated models.

And, `generate()`write these models to files.
https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/__init__.py#L336

> type(...)

We can get rendered model by calling str(model).
https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/model/base.py#L123-L124


> Another use-case (although less important) would be to 'translate' the schema into a different format (I would have a use for Avro, for example). Basically, datamodel-code-generator could become sort of an any-to-any schema translator. 

I hope datamodel-code-generator can become an any-to-any schema translator. So, I don't call the project `pydantic-code-generator` or `openapi-to-pydantic`.
I designed the code-generator can support multitype input/output types.
We have to implement a class inherited from `Parser` that each input type.
This class is for `JsonSchema`.
We can implement other classes for other input types.
https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/parser/jsonschema.py#L221

Also, I explain about output type. This class is for Pydantic's `BaseModel`.
https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/model/pydantic/base_model.py#L76
We can add other output types by implementing Other `DataModel` like [enum.Enum ](https://github.com/koxudaxi/datamodel-code-generator/blob/1c3a842373108f54a2c170524189e919bf9cae91/datamodel_code_generator/model/enum.py#L10)


I know we must write more documents to show how to use it. But, I'm busy :(
https://github.com/koxudaxi/datamodel-code-generator/issues/133

Some user requests supporting another type(like [gRPC](
https://github.com/koxudaxi/datamodel-code-generator/issues/200)). I want to implement it when I get the time.

**Comment by makkus** [comment]
Thanks a lot for the very detailed response, @koxudaxi . When adding this issue I only had a look at the 'generate' method that is used in the workaround you mentioned, which is why I assumed the project was more tightly coupled than it actually is. Good to know that the necessary modularity is already there!

It seems doable to implement a DataModel for my use-case, so I will try to do that, I'm sure I'll figure out how without any extra documentation. I'm currently at the 'investigate-options' phase of our project, so this is not very urgent for me, and it will take me some time to get started on it anyway. So feel free to close that issue.

**Comment by koxudaxi** [comment]
Sounds good! I have closed this issue.
If you have any question or  idea then, please open a new issue or use [discussions](https://github.com/koxudaxi/datamodel-code-generator/discussions)

Thank you.

**Comment by timini** [comment]
Is it possible to generate a model from jsonschema and use that model at runtime?

**Comment by nor3th** [comment]
Hey @timini 

The most dynamic approach for loading a json schema model at runtime I have found so far would be this one:
```
import importlib
import json
import os
from enum import Enum
from pathlib import Path

from datamodel_code_generator import generate, InputFileType
from pydantic import BaseModel


class Age(str, Enum):
    young = 1
    old = 2

class TestModel(BaseModel):
    id: int
    name: str
    street: str
    age: Age

schema = TestModel.schema_json()
name = json.loads(schema).get('title')

output = Path(f"./{name}.py")
generate(
        schema,
        input_file_type=InputFileType.JsonSchema,
        input_filename="example.json",
        output=output,
)
_tmp = importlib.import_module(f"{name}")
os.remove(f"./{name}.py")
model = getattr(_tmp, name)
print(model.__signature__)
```

@koxudaxi 
I wasn't able to get the model into runtime from the parser directly like this. Any hint on how to call the parser which would then return a BaseModel class?
```
parser = JsonSchemaParser(
        source=schema,
        base_class='pydantic.BaseModel',
        custom_template_dir=None,
        extra_template_data=None,
        target_python_version=PythonVersion.PY_37,
        dump_resolve_reference_action=dump_resolve_reference_action,
        validation=False,
        field_constraints=False,
        snake_case_field=False,
        strip_default_none=False,
        aliases=None,
        allow_population_by_field_name=False,
        apply_default_values_for_required_fields=False,
        force_optional_for_required_fields=False,
        class_name=None,
        use_standard_collections=False,
        base_path=None,
        use_schema_description=False,
        reuse_model=False,
        enum_field_as_literal=None,
        set_default_enum_member=False,
        strict_nullable=False,
        use_generic_container_types=False,
        enable_faux_immutability=False,
        remote_text_cache=DefaultPutDict(),
        disable_appending_item_suffix=False,
        strict_types=None,
        empty_enum_field_name=None,
        custom_class_name_generator=None,
        field_extra_keys=None,
        field_include_all_keys=False,
        wrap_string_literal=None,
        use_title_as_name=False,
        http_headers=None,
        http_ignore_tls=False,
        use_annotated=False,
        use_non_positive_negative_number_constrained_types=False
    )

result = parser.parse()
print(result)
```

**Comment by NiklasvonM** [comment]
Hi @nor3th,

I have a different approach that uses `io.StringIO` and `contextlib.redirect_stdout` so that no file is created:
```python
from contextlib import redirect_stdout
from io import StringIO
from datamodel_code_generator import InputFileType, generate

with StringIO() as output_buffer, redirect_stdout(output_buffer):
    generate(json_schema, input_file_type=InputFileType.JsonSchema)
    generated_code: str = output_buffer.getvalue()
namespace = {}
exec(generated_code, namespace)
Model = list(namespace.values())[-1]
assert issubclass(Model, BaseModel)
```
See my [gist](https://gist.github.com/NiklasvonM/c9c596826d8445a1a1823a0a8fae1fbb) for a runnable example.

Note that this approach is potentially dangerous as it uses `exec` to execute the code that was generated by datamodel-code-generator. However, I am not sure if it is much more dangerous than importing the generated model code using importlib.

**Comment by bhavan-kaya** [comment]
I'm trying to dynamically create a Pydantic model using a function that takes a dictionary as input. I'm using the `create_model` function to generate the model class dynamically based on a configuration dictionary. 


Here's my code:

```python
from typing import Type
from pydantic import BaseModel, create_model, Field

# Step 1: Load the JSON
config = {
    "input_parameters": {
        "query": "string",
        "employeeId": "int"
    }
}

# Step 2: Generate the dynamic Pydantic model using the input_parameters from the config
def create_dynamic_model(parameters: dict) -> Type[BaseModel]:
    fields = {}
    type_mapping = {
        "string": (str, ...),  # Required field
        "int": (int, ...),
        "float": (float, ...),
        "bool": (bool, ...),
        "list": (list, ...),
        "dict": (dict, ...)
    }

    for param_name, param_type in parameters.items():
        if param_type in type_mapping:
            fields[param_name] = (
                type_mapping[param_type][0],
                Field(..., description=f"{param_name} of type {param_type}")
            )
        else:
            raise ValueError(f"Unsupported parameter type: {param_type}")

    # Create a dynamic model
    DynamicModel = create_model('DynamicInputModel', **fields)
    return DynamicModel

# Create the dynamic input model based on the input_parameters in the JSON
input_parameters = config.get("input_parameters", {})
DynamicInputModel = create_dynamic_model(input_parameters)
```
