### ISSUE TITLE
Add ability to enable faux immutability for every model

### ISSUE THREAD

**Issue by ofek** [koxudaxi/datamodel-code-generator#337]
**Is your feature request related to a problem? Please describe.**

Same as https://github.com/koxudaxi/datamodel-code-generator/issues/334

> We have immutability requirements and therefore do not use `list`/`typing.List` nor `dict`/`typing.Dict`

**Describe the solution you'd like**

The option would ensure that every generated model has a config with `allow_mutation = False`

https://pydantic-docs.helpmanual.io/usage/models/#faux-immutability

**Describe alternatives you've considered**

In my feature branch I have a post-generation step that modifies the output file

**Comment by koxudaxi** [comment]
@ofek 
I have released a new version `0.7.3` 
The version has `--enable-faux-immutability`

**Comment by ofek** [comment]
Wow that was quick, thanks!!!
