### ISSUE TITLE
specify input_filename when used as module

### ISSUE THREAD

**Issue by tstorek** [koxudaxi/datamodel-code-generator#349]
**Describe the bug**

Hello,

thanks, for this really handy tool. However, I discovered either an ill documented or really unexpected behavior when using the generator  a module  according to this example: 

https://github.com/koxudaxi/datamodel-code-generator/blob/master/docs/using_as_module.md

The example works as expected, but when using a dirpath for 'input_' and simultaneously give an input_filename I would expect that the generator is searching the directory for the specific file. But instead, it tries to parse the first file in the directory.

Hence, I do not understand the purpose of 'input_filename'. In the CLI it is also not even used. Maybe documentation helps here

**To Reproduce**

- one other file with random content but named alphabetically before schema-example.json
- json-file (schema-example.json) with the following content:
```

{
    "type": "object",
    "properties": {
        "number": {"type": "number"},
        "street_name": {"type": "string"},
        "street_type": {"type": "string",
                        "enum": ["Street", "Avenue", "Boulevard"]
                        }
    }
}


```

Used script code:

```
import os
import shutil
from pathlib import Path
from tempfile import TemporaryDirectory
from datamodel_code_generator import InputFileType, generate

json_schema: str = """{
    "type": "object",
    "properties": {
        "number": {"type": "number"},
        "street_name": {"type": "string"},
        "street_type": {"type": "string",
                        "enum": ["Street", "Avenue", "Boulevard"]
                        }
    }
}"""

if __name__ == '__main__':
    path = Path(os.getcwd()).joinpath("../datamodels")
    path.mkdir(parents=True, exist_ok=True)
    with TemporaryDirectory() as temp:
        temp = Path(temp)
        output = Path(temp).joinpath('model.py')
        input = Path(os.getcwd())
        generate(
            input_=input,
            input_file_type=InputFileType.JsonSchema,
            input_filename="schema-example.json",
            output=output,
        )
        filename = path.joinpath('example.py')
        shutil.move(str(output), str(filename))
```

**Expected behavior**
I expect parsing of the file specified in input_filename or a descriptive error message if the file cannot be found

**Version:**
 - OS: windows10
 - Python version: 3.8
 - datamodel-code-generator version: 0.6.9

**Additional context**

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I'm sorry, The workaround is not clear.
`input_` should be an absolute Path or strings of contents.
If you pass a directory as `Path` then, the code-generator parse all file.  
```python
import os
import shutil
from pathlib import Path
from tempfile import TemporaryDirectory
from datamodel_code_generator import InputFileType, generate

json_schema: str = """{
    "type": "object",
    "properties": {
        "number": {"type": "number"},
        "street_name": {"type": "string"},
        "street_type": {"type": "string",
                        "enum": ["Street", "Avenue", "Boulevard"]
                        }
    }
}"""
input_filename = 'schema-example.json'

with open(input_filename, 'w') as f:
    f.write(json_schema)

if __name__ == '__main__':
    path = Path(os.getcwd()).joinpath("../datamodels")
    path.mkdir(parents=True, exist_ok=True)
    with TemporaryDirectory() as temp:
        temp = Path(temp)
        output = Path(temp).joinpath('model.py')
        generate(
            input_=Path(input_filename).absolute(),
            input_file_type=InputFileType.JsonSchema,
            output=output,
        )
        filename = path.joinpath('example.py')
        shutil.move(str(output), str(filename))

```


> Hence, I do not understand the purpose of 'input_filename'. In the CLI it is also not even used. Maybe documentation helps here

Yes, CLI doesn't use it. I expect this case.
```python
...
        generate(
            input_=json_schema, # str
            input_file_type=InputFileType.JsonSchema,
            output=output,
            input_filename=input_filename
        )
...
```

However, This behavior may confuse you and other users. I may remove the option in the future version. 🤔

**Comment by koxudaxi** [comment]
@tstorek 
I have relased a new version as `0.8.2`
The version fixed the relative path problem on the input file.
You can pass the `Path` of a file or directory without getting an absolute path.
 
```python
    generate(
                input_=Path(input_filename),
                input_file_type=InputFileType.JsonSchema,
                output=output,
            )
```
