### ISSUE TITLE
Allow custom base class for models

### ISSUE THREAD

**Issue by MrMrRobat** [koxudaxi/datamodel-code-generator#37]
**Is your feature request related to a problem? Please describe.**
Didn't use this library yet, just looked at code and saw that `BaseModel` is hardcoded in templates as base class for models:
https://github.com/koxudaxi/datamodel-code-generator/blob/f7f00459e9cccede79cec827f7c77557754306a2/datamodel_code_generator/model/template/pydantic/BaseModel.jinja2#L4

**Describe the solution you'd like**
Add ability to choose the name of base class of models (and even create one automatically)
This would be helpful if I wan't to have same config, methods, etc for all subclasses

**Describe alternatives you've considered**
This can be approached by renaming `BaseModel` in a result manually, but if it not hard to implement I'd preffered to have this built-in 

**Additional context**

**Comment by koxudaxi** [comment]
@MrMrRobat 
Sounds great to me.

> This can be approached by renaming BaseModel in a result manually, but if it not hard to implement I'd preffered to have this built-in

Did you expect to use inherited `BasdModel`?

I think the code generator should able to receive the alternative base class as arguments or a config file.

**Comment by koxudaxi** [comment]
@MrMrRobat 
support and publish the feature. Thank you
## Example 
`$ datamodel-codegen --input ./tests/data/api.yaml --base-class custom_module.CustomBase`
Output:
```python
class Pet(CustomBase):
    id: int
    name: str
    tag: Optional[str] = None
...
```

**Comment by MrMrRobat** [comment]
Looks great, thank you!
