### ISSUE TITLE
Generated data has circular imports?

### ISSUE THREAD

**Issue by larsks** [koxudaxi/datamodel-code-generator#392]
**Describe the bug**

I'm trying to use `datamodel-codegen` to produce Pydantic models from OpenShift resources. While the command completes successfully and generates a hierarchy of Python modules, attempting to import anything results in:

```
>>> import generated
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/projects/operate-first/acm-clusterdeployment-generator/generated/__init__.py", line 13, in <module>
    from .com.github.openshift.api.image import v1
  File "/home/lars/projects/operate-first/acm-clusterdeployment-generator/generated/com/github/openshift/api/image/v1.py", line 11, in <module>
    from ...... import Annotations9, Blobs, Images, SignedClaims
ImportError: cannot import name 'Annotations9' from partially initialized module 'generated' (most likely due to a circular import) (/home/lars/projects/operate-first/acm-clusterdeployment-generator/generated/__init__.py)
```

**To Reproduce**

I've started with the OpenShift schema available from `https://<your_openshift_server>/openapi/v2`. This produces a 17MB output file ([here](https://gist.github.com/58ae7b9c912dd575b2858731e6335c50) if you want to see it). I save this output to `openshift.json` and then run:

```
datamodel-codegen --input openshift.json --input-file-type jsonschema --output generated/
```

Example schema:

- https://gist.github.com/58ae7b9c912dd575b2858731e6335c50

Used commandline:
```
$ datamodel-codegen --input openshift.json --input-file-type jsonschema --output generated/
```

**Expected behavior**

I expect to be able to do something like:

```
from generated.io.k8s.api.core.v1 import Secret
```

**Version:**

 - OS: Linux (fedora 33)
 - Python version: 3.9.2
 - datamodel-code-generator version: 0.9.4

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I have found a bug.
This problem is related to the issue https://github.com/koxudaxi/datamodel-code-generator/issues/244
I will fix it.

## deep dive into the problem

Annotations9 is referenced from `generated.com.github.openshift.api.image.TagReference`

```python
class TagReference(BaseModel):
    annotations: Optional[Dict[str, Annotations9]] = Field(
        None,
        description='Optional; if specified, annotations that are applied to images retrieved via ImageStreamTags.',
    )

```

I search the description from the schema.
```json
"com.github.openshift.api.image.v1.TagReference":
  {"description":"TagReference specifies optional annotations for images using this tag and an optional reference to an ImageStreamTag, ImageStreamImage, or DockerImage this tag should track.",
   "type":"object",
   "required":["name"],
   "properties":
      {"annotations":
          {"description":
            "Optional; if specified, annotations that are applied to images retrieved via ImageStreamTags.",
             "type":"object",
             "additionalProperties":{"type":"string"}
             },
```
The code-generator detects the model as a modular model.
`"com.github.openshift.api.image.v1.TagReference":`
And, the model will be generated in in `com.github.openshift.api.image.v1`
But, a model (a.k.a `Annotations9`) will be generated as no-modular model on top-level.
So, the relation causes the `ImportError`
`Annotations9` have to be generated in `com.github.openshift.api.image.v1`.

**Comment by larsks** [comment]
Thanks for the detailed description of the problem!

**Comment by koxudaxi** [comment]
@larsks 
I have released a fixed version `0.10.0`. 🚀 
openshif.json is a huge schema. I don't check all models.
If you find any problem in generated models then please tell me it.
Thank you.

```bash
$ datamodel-codegen --version
0.10.0
$ datamodel-codegen --input openshift.json  --input-file-type jsonschema  --output generated/
/Users/koudai/PycharmProjects/pythonProject10/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:337: UserWarning: format of 'semver' not understood for 'string' - using default
  warn(
/Users/koudai/PycharmProjects/pythonProject10/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:337: UserWarning: format of 'int-or-string' not understood for 'string' - using default
  warn(
/Users/koudai/PycharmProjects/pythonProject10/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:337: UserWarning: format of 'duration' not understood for 'string' - using default
  warn(
$ python3
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from generated.io.k8s.api.core.v1 import Secret
>>> Secret()
Secret(apiVersion=None, data=None, immutable=None, kind=None, metadata=None, stringData=None, type=None)

```

**Comment by harshach** [comment]
@koxudaxi I am using 0.11.4 and still running into circular imports issue with openapi v3 schema. Is this fixed or still an open issue?

**Comment by harshach** [comment]
Never mind! this is an issue on my schema side. Thanks
