### ISSUE TITLE
--enum-field-as-literal=one converts integer to string

### ISSUE THREAD

**Issue by goodoldneon** [koxudaxi/datamodel-code-generator#440]
**Describe the bug**

When using the `--enum-field-as-literal=one` arg, the generated literal is always a string. Even if you explicitly set `type: integer`.

**To Reproduce**

Example schema:
```yaml
Foo:
  type: object
  properties:
    bar:
      type: integer
      enum: [1]
```

Creates:

```py
class Foo(BaseModel):
    bar: Optional[Literal['1']] = None
```

Used commandline:
```
$ datamodel-codegen --input openapi.yaml --output models.py --enum-field-as-literal=one
```

**Expected behavior**

If an enum type is `integer` then the resulting literal is also an integer.

**Version:**
 - OS: macOS `11.4`
 - Python version: `3.9.2`
 - datamodel-code-generator version: `0.11.6`

**Additional context**

This appears to be a problem with this type:

https://github.com/koxudaxi/datamodel-code-generator/blob/master/datamodel_code_generator/types.py#L74

Changing that type to `List[int]` results in an int literal. Not that we should change the type to `List[int]` specifically, but rather that the type likely needs to be more flexible.

**Comment by koxudaxi** [comment]
Thank you for creating this issue.

> If an enum type is integer then the resulting literal is also an integer.

I didn't expect integer or other literal types. :cry: 

> Changing that type to List[int] results in an int literal. Not that we should change the type to List[int] specifically, but rather that the type likely needs to be more flexible.

Yes, it should accept other types too.

**Comment by duesenfranz** [comment]
This Problem somehow reappeared in version `0.11.9`!

**Comment by duesenfranz** [comment]
Ah sorry, I don't think this actually depends on the version of `datamodel-code-generator`. Instead, the problem is still reproducible for me with `Jinja2==3.0.2`, but disappears after installing `Jinja2==2.11.3` instead.
