### ISSUE TITLE
Tests folder installed in site-packages

### ISSUE THREAD

**Issue by jaraqueffdc** [koxudaxi/datamodel-code-generator#453]
**Describe the bug**
I am not sure if this is a bug or something weird I am not understanding but when I installed the package, the tests folder was installed within `site-packages` instead of within this library folder which is causing that anything with my project's tests module is not importable. Within site-packages I can see the `datamodel_code_generator` library but then I noticed that there is a `tests` which is in conflict with my project's `tests` module.

Since I am using conda I have a pth file for my project's modules there and they do not take priority over site-packages ones. This is causing that when I try to import something from tests like `from tests.blah import Blah` it will say that `tests.blah` does not exist because it is trying to find it within the tests module of `datamodel-code-generator`.

**To Reproduce**
I just installed the package in a conda environment as normal. This caused the tests folder to be within `site-packages` instead of contained within its own package.

**Expected behavior**
I would expect that the tests of the code generator are contained within the code generator package when installed. This can cause any project that is not setting their own modules via sys.path or PYTHONPATH to have conflicts if they have a module named tests they need to import. Since conda supports pth files within site-packages to define where to find local modules for a given environment this can be an issue for anyone using conda.

**Version:**
 - OS: MacOS 11.4
 - Python version: 3.8.5
 - datamodel-code-generator version: 0.11.7

**Comment by koxudaxi** [comment]
@jaraqueffdc 
Thank you for creating this issue.
I have not used `conda` yet. 
I watch a virtual env directory.
But, I can't find the `tests`  directory.
I will try `conda` to reproduce your problem.

```bash
 ls -1 venv/lib/python3.9/site-packages/datamodel_code_generator*
venv/lib/python3.9/site-packages/datamodel_code_generator:
__init__.py
__main__.py
__pycache__
format.py
http.py
imports.py
model
parser
reference.py
types.py
version.py

venv/lib/python3.9/site-packages/datamodel_code_generator-0.11.3.dist-info:
entry_points.txt
INSTALLER
LICENSE
METADATA
RECORD
REQUESTED
top_level.txt
WHEEL
zip-safe


```

**Comment by jaraqueffdc** [comment]
Thanks! Just to let you know, I use conda but I intalled the package with pip so the installation should be the same as in a venv (not sure if there are any subtle differences I am not aware of).

The issue is not that the tests directory is within the installed package but that it appeared in the `site-packages` folder, i.e. one level above what makes it an importable module by itself hence shadowing other tests modules I could have in my own project.

I do not remember having done anything special with this package when I installed it so I am guessing this is something that might have happened automatically for some weird reason. I just moved the tests folder within the package directory and it is ok now. I wanted to raise the issue in case there is something odd with the installation process that can cause this for someone else.

Thanks a lot for taking a look and thanks for this package! We have several objects returned by an API with hundreds of field... a total lifesaver!

**Comment by koxudaxi** [comment]
OK, I understand your situation when occurring the problem.
I don't usually use `macOS` and `Conda`. 
I will try to reproduce the problem tomorrow after preparing the environment.

**Comment by gaborbernat** [comment]
This is very much an issue with virtualenv. Easy to reproduce:

```
curl  https://files.pythonhosted.org/packages/59/48/10fb065a02e3f14aaa6e7548a81556650de90e3140d4cce1e5953d9a0ce3/datamodel_code_generator-0.11.8-py3-none-any.whl -o datamodel_code_generator-0.11.8-p
y3-none-any.whl

zipinfo ./datamodel_code_generator-0.11.8-py3-none-any.whl | grep 'tests/' | wc -l
360
```

**Comment by jaraqueffdc** [comment]
Great thanks!
