### ISSUE TITLE
Split long descriptions on multiple lines

### ISSUE THREAD

**Issue by gaborbernat** [koxudaxi/datamodel-code-generator#456]
Description strings are currently injected as a single line, which is troublesome for long strings. We should ideally split them across multiple lines in such cases:

```python
class Cfg(BaseModel):
    b: Optional[str] = Field(
        None,
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut arcu velit, fringilla nec enim dictum, luctus  bibendum dui. Maecenas eget ex ac velit auctor mollis. Integer enim ex, pharetra sed sapien id, tincidunt fermentum eros.",
    )
```

```python
class Cfg(BaseModel):
    b: Optional[str] = Field(
        None,
        description=(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut arcu velit, fringilla nec enim dictum, luctus "
            "bibendum dui. Maecenas eget ex ac velit auctor mollis. Integer enim ex, pharetra sed sapien id, tincidunt"
            " fermentum eros."
        ),
    )

```

For this the user should perhaps pass some target line length 👍

**Comment by koxudaxi** [comment]
Thank you for your great suggestion.
OK, I will add the CLI Option.

**Comment by gaborbernat** [comment]
How come the generated strings are now quoted with `'` instead of `"`?

**Comment by koxudaxi** [comment]
@gaborbernat 
I'm sorry for my late reply 🙇 

> How come the generated strings are now quoted with ' instead of "?

I think the problem is related `skip-string-normalization`  option in toml.
Could you show me your pyproject.toml?
