### ISSUE TITLE
setuptools test_requires is deprecated

### ISSUE THREAD

**Issue by gaborbernat** [koxudaxi/datamodel-code-generator#458]
setuptools test_requires is deprecated https://github.com/koxudaxi/datamodel-code-generator/blob/master/setup.cfg#L43-L53 - see https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies, instead consider using https://tox.readthedocs.io/en/latest for example see https://github.com/pypa/virtualenv/blob/main/tox.ini

**Comment by koxudaxi** [comment]
@gaborbernat 
I will able to change it this weekend.
Thank you!!

**Comment by koxudaxi** [comment]
I have removed `setup.cfg`. Because this project will use poetry. 

Thank you!!
