### ISSUE TITLE
Support JsonSchemaObject's additionalProperties: false

### ISSUE THREAD

**Issue by reb00ter** [koxudaxi/datamodel-code-generator#471]
As solution for issue https://github.com/koxudaxi/datamodel-code-generator/issues/82 has been added support for `additionalProperties: true`, but false values are ignored. And there is no way to restrict adding properties for model

Would be great, to have `extra = Extra.forbid` config option for models with `additionalProperties: false` param

Trying to set this option for base model, but in my case I have base-models with `additionalProperties: true`, which includes in `allOf` for models with `additionalProperties: false`. So permit param value overrides base model setting

**Comment by ghandic** [comment]
Surely this should be `extra = 'ignore'` ? Any chance this could be a switch?
