### ISSUE TITLE
Use title for generating the names of objects inside anyOf/oneOf

### ISSUE THREAD

**Issue by gaborbernat** [koxudaxi/datamodel-code-generator#483]
Currently the root key is used, but this has the side effect of elements being named as `RootItem1`, `RootItem2`, etc 👍

**Comment by koxudaxi** [comment]
@gaborbernat 
Thank you for your great idea.
I think we can use the idea for other types like `array`, `enum`, etc.
What do you think about it?

I will expect to add a new CLI option for the idea.
Because I wouldn't like to break the current behavior.

**Comment by gaborbernat** [comment]
Sounds great to me :+1:
