### ISSUE TITLE
Use Annotated instead of cons variants

### ISSUE THREAD

**Issue by gaborbernat** [koxudaxi/datamodel-code-generator#492]
The cons variants are not supported by mypy, instead one can use the Annotated form:

```python
class A(BaseModel):
     p: constr(min_length=1)
```

Because the type here becomes constr that to the type checker seems a new type, not a variant of str: https://www.python.org/dev/peps/pep-0593/ With the introduction of PEP-593 now instead one should do:

```python
class A(BaseModel):
     p: Annotated[str, Field(min_length=1)]
```

Now mypy will handle correctly both ``A().p`` and ``A().p = "b"``.

For more details see https://github.com/samuelcolvin/pydantic/issues/156

**Comment by koxudaxi** [comment]
@gaborbernat 
Thank you for suggesting the idea.
I know about `Annotated`. 
I will implement the feature as a CLI option. :wink:
