### ISSUE TITLE
Publish this package on pypi

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/datamodel-code-generator#5]
I will try to publish the package soon.

**Comment by joshbode** [comment]
see my PR :)

**Comment by joshbode** [comment]
If you push a tag, I think the build should upload to pypi (if we're lucky!)

**Comment by joshbode** [comment]
Oops, I think we need to add `long_description_content_type = text/markdown` to the metadata section of `setup.cfg`

This is the error on upload in the build logs:
```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/```

**Comment by joshbode** [comment]
Just saw your commit

**Comment by koxudaxi** [comment]
Thank you for watching the repo :)

**Comment by joshbode** [comment]
Looks like both sub-builds are uploading and the one that gets in second is failing...
Going to bed now, but I'll look at how we can conditionally upload on only one of the builds (3.7 maybe)
In any case, the package is on PyPI!

**Comment by koxudaxi** [comment]
Thank you for following me. 
I'm looking for it too.
