### ISSUE TITLE
pip install datamodel-code-generator[http] not working

### ISSUE THREAD

**Issue by eg-firebolt** [koxudaxi/datamodel-code-generator#508]
**To Reproduce**

In a fresh virtualenv, I am not able to install with [http] option as described by the README. 

```shell
❯ pip install datamodel-code-generator[http]
zsh: no matches found: datamodel-code-generator[http]
```

Usual install without http option works fine

**Version:**
 - OS: macOS
 - Python version: 3.9

**Comment by koxudaxi** [comment]
@eg-firebolt 
Thank you for creating this issue.
You should escape the `[ ]` because zsh detects `[ ]` as a special character.

```
$ pip install datamodel-code-generator\[http\]
```
or 
```
$ pip install "datamodel-code-generator[http]"
```

We should write the topic on README.
