### ISSUE TITLE
Generate proper type for `nullable` but required fields

### ISSUE THREAD

**Issue by shreyas44** [koxudaxi/datamodel-code-generator#551]
**Is your feature request related to a problem? Please describe.**

Currently if `nullable` is set to `True` in the schema definition, the generated type is an `Optional`. Though this isn't wrong, there are still 2 things that aren't covered:
1. The field is nullable but required
2. While generating the json schema from the model, `nullable` isn't in the output

**Describe the solution you'd like**
1. To make sure the nullable property is in the output schema, we can add `nullable=True` as an argument to `Field`

```py
class Foo(BaseModel):
  a: Optional[str] = Field(nullable=True)
```

2. For required nullable fields, the below solution works

```py
class Foo(BaseModel):
  a: Optional[str] = Field(..., nullable=True)
```

Passing `...` as the first argument to `Field` [marks the field as required](https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation) and an error is raised if we don't pass a value for `a`. And, since the type of the field is `Optional[str]` it means we can still pass `None` as a valid value.

**Comment by koxudaxi** [comment]
@shreyas44 
I'm sorry for my response late.

> 1. The field is nullable but required

You can use `--strict-nullable` option to get `Optional[str] = Field(...)`
```
  --strict-nullable     Treat default field as a non-nullable field (Only OpenAPI)
```

> 2. While generating the json schema from the model, nullable isn't in the output

I don't know any idea. If you need the result then I must change `--field-extra-keys ` option.
The option passes extra keys. But, `nullable` is ignored now.
