### ISSUE TITLE
Predictable code generation

### ISSUE THREAD

**Issue by josemonteiro** [koxudaxi/datamodel-code-generator#579]
**Is your feature request related to a problem? Please describe.**
Code generated by different systems (e.g. different OS like Linux and Mac) can be different, because Python classes can be output in different order. 

**Describe the solution you'd like**
Code generated should be the same regardless of system used to generate it. This allows reproducible builds and validation in CI/CD systems.

**Describe alternatives you've considered**
Changing generated files with a tool similar to isort but for classes - couldn't find any!

**Comment by andreffs18** [comment]
This would be great! Really looking for this!

**Comment by captainvera** [comment]
This would be really cool as it sometimes introduces unforeseen problems in our use case :)

**Comment by andreffs18** [comment]
🚀 🙏

**Comment by koxudaxi** [comment]
@josemonteiro  @andreffs18 @captainvera 
I'm sorry that my action is too late.
I have released a new version, `0.17.0` .
The version has a new option, `--keep-model-order `
Thank you very much!!

**Comment by josemonteiro** [comment]
Thank you @koxudaxi!

**Comment by captainvera** [comment]
Thank you! @koxudaxi
