### ISSUE TITLE
Unable to use aliases to change 'type' to 'type_'

### ISSUE THREAD

**Issue by cclauss** [koxudaxi/datamodel-code-generator#600]
**Describe the bug**

What is the best way to deal with json data that uses the key `type` which is a Python reserved word?

I would like to create a data model as follows...
% `datamodel-codegen --url https://openlibrary.org/isbn/0140328726.json`
```
Invalid file format
```
So, I copy the json to a local file...
% `datamodel-codegen --input ./isbn_0140328726.json`
```
pydantic.error_wrappers.ValidationError: 2 validation errors for JsonSchemaObject
type
  str type expected (type=type_error.str)
type
  value is not a valid list (type=type_error.list)
```
I assume the problem it that the json contains keys named `type` which is a Python keyword so I want to create an alias to change `type` to `type_`

% `cat datamodel-codegen-aliases.json`
```
{"type": "type_"}
```
% `datamodel-codegen --input isbn_0140328726.json --aliases ./datamodel-codegen-aliases.json`
```
[ Same output as before. ]
```

**To Reproduce**

Example schema:
```json

 ADD EXAMPLE HERE

```

Used commandline:
```
$ datamodel-codegen ADD YOUR EXACT COMMAND USED HERE
```

**Expected behavior**

**Version:**
 - Python version:
 - datamodel-code-generator version: [e.g. 22]

**Additional context**

**Comment by koxudaxi** [comment]
@cclauss 
Thank you for reporting the problem.
I will fix it.
