### ISSUE TITLE
Create pre-commit hooks

### ISSUE THREAD

**Issue by benjaminsky** [koxudaxi/datamodel-code-generator#616]
I'd like to be able to limit the number of CI failures by running codegen as a [pre-commit](https://pre-commit.com/) hook.  I'm thinking something similar to [this](https://github.com/tj-pre-commit/graphql-codegen-hook)

**Comment by koxudaxi** [comment]
Now, `datamodel-code-generator` supports `pre-commit`
https://github.com/koxudaxi/datamodel-code-generator/pull/1416
