### ISSUE TITLE
mypy constraint error

### ISSUE THREAD

**Issue by adaamz** [koxudaxi/datamodel-code-generator#625]
**Describe the bug**
When some constraint (min/max length etc) is used, then generator uses pydantic's constraint function which somehow confuses mypy which then marks this as an error (https://stackoverflow.com/questions/67009123/how-can-mypy-accept-pydantics-constr-types). This erorr can be workarounded by creating constraint class and defining constraint inside as properties (viz. stackoverflow thread).

**To Reproduce**

Example schema:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Some endpoint
paths:
  some_endpoint:
    parameters:
      type: object
      properties:
        md5_hash:
          type: string
          minLength: 32
          maxLength: 32
```

generates this python script:
```python
# generated by datamodel-codegen:
#   filename:  the_schema.yml
#   timestamp: 2021-11-25T17:43:29+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, constr


class SomeEndpointRequest(BaseModel):
    md5_hash: Optional[constr(min_length=32, max_length=32)] = None
```

Used commandline:
```
datamodel-codegen --input the_schema.yml --output the_schema.py
pip install mypy
mypy the_schema.py
```
output of mypy:
```
the_schema.py:13: error: Invalid type comment or annotation
the_schema.py:13: note: Suggestion: use constr[...] instead of constr(...)
```

**Expected behavior**
Mypy throws no type error.

**Version:**
 - OS: linux
 - Python version: 3.9
 - datamodel-code-generator version: 0.11.14

**Comment by koxudaxi** [comment]
@adaamz 
I know the problem.
You can use `--field-constraints` option to avoid the error.

`  --field-constraints   Use field constraints and not con* annotations`

Output
https://github.com/koxudaxi/datamodel-code-generator/blob/master/tests/data/expected/main/main_with_field_constraints/output.py

**Comment by adaamz** [comment]
Thank you for your answer.
I'm thinking why is not this setting the default behavior. Is constr type better somehow? or is it just because of bc break in behavior? :)

**Comment by koxudaxi** [comment]
@adaamz 
> or is it just because of bc break in behavior? :)

Exactly, Many users don't want to change the current behavior.
We improve the code-generator by CLI options
