### ISSUE TITLE
Support for `extends`

### ISSUE THREAD

**Issue by pmbrull** [koxudaxi/datamodel-code-generator#686]
**Is your feature request related to a problem? Please describe.**
JSON Schema to POJO (https://www.jsonschema2pojo.org/) supports the `extends` keyword to handle class hierarchies. We are working on a project that has a single model definition in terms of JSON Schemas and multiple codebases in different languages based on that.

It would be great if the pydantic model generation supported this as well.

**Describe the solution you'd like**

Following the docs:

`flower.json`:
```json
    {
        "type" : "object"
    }
```

and `rose.json`:
```json
    {
        "type" : "object",
        "extends" : {
            "$ref" : "flower.json"
        }
    }
```

should generate:

```python
class Flower(BaseModel):
    ...

class Rose(Flower):
    ...
```

**Describe alternatives you've considered**
No alternatives atm. The current approach would be not using the `extends` at all for compatibility with all languages.

---

Many thanks 🙏

**Comment by goodoldneon** [comment]
Unless I'm overlooking something, `extends` isn't in the Open API or JSON Schema specs. Is there behavior you need that `$ref` doesn't already support?

This OpenAPI:

```yml
openapi: "3.1.0"
components:
  schemas:
    Foo:
      type: object
      properties:
        a:
          type: string
    Bar:
      allOf:
        - $ref: "#/components/schemas/Foo"
        - type: object
          properties:
            b:
              type: string
```

Generates these models:

```py
class Foo(BaseModel):
    a: Optional[str] = None


class Bar(Foo):
    b: Optional[str] = None
```

**Comment by pmbrull** [comment]
You're right @goodoldneon, nice catch. We could already use `$ref`. Thanks!

Let's close this :)
