### ISSUE TITLE
Strings in the generated models are not compatible with black formatter

### ISSUE THREAD

**Issue by pawelrubin** [koxudaxi/datamodel-code-generator#731]
**Is your feature request related to a problem? Please describe.**
Strings in the generated models are single-quoted, which is incompatible with **black** formatter.

**Describe the solution you'd like**
Double quotes are the default.

**Describe alternatives you've considered**
There is a configuration option for which quotes to use.

**Comment by koxudaxi** [comment]
Hi @pawelrubin 
The code generator supports the config files for `balck`.
If you have your preferred option then please set it in the file.

https://koxudaxi.github.io/datamodel-code-generator/formatting/

**Comment by pawelrubin** [comment]
The **black** formatter does not allow the configuration of string quoting.

**Comment by nesb1** [comment]
Hello! I need this option so much, because I use datamodel-codegen without `--output` option (due to the specifics of my task, i create python module myself). And so i have quotes conflict.

**Comment by nesb1** [comment]
PR https://github.com/koxudaxi/datamodel-code-generator/pull/818
