### ISSUE TITLE
Add `requestBodies` option to `--openapi-scopes`

### ISSUE THREAD

**Issue by dflantz** [koxudaxi/datamodel-code-generator#741]
**Is your feature request related to a problem? Please describe.**
I would like to document request bodies in OpenAPI's dedicated `#/components/requestBodies` section, however, it is not currently picked up by datamodel-codegen. See openapi doc on [describing request bodies](https://swagger.io/docs/specification/describing-request-body/).

**Describe the solution you'd like**
Add a `requestBodies` option to the `--openapi-scopes` CLI arg, and generate the objects defined therein

**Describe alternatives you've considered**
Using the `schemas` section, but for large and complex API, it helps with readability to have one dedicated section to requestBodies

**Comment by koxudaxi** [comment]
Hi @dflantz 
`--openapi-scopes paths` supports parsing `requestBody`
Could you please try it?

**Comment by mayn** [comment]
@koxudaxi 
```
datamodel-codegen: error: argument --openapi-scopes: invalid choice: 'requestBodies' (choose from 'schemas', 'paths')
datamodel-codegen --version                      
0.14.0
```

**Comment by koxudaxi** [comment]
@mayn 
You should do `datamodel-codegen --input inputfile.yaml --openapi-scopes paths`

**Comment by koxudaxi** [comment]
no response :(
