### ISSUE TITLE
Combining "required" and "default" leads to an optional property

### ISSUE THREAD

**Issue by ogenstad** [koxudaxi/datamodel-code-generator#757]
**Is your feature request related to a problem? Please describe.**

Marking a property as required in combination of having a default value is still marked as optional in the Python module.

schema.json
```json
{
    "$id": "https://example.com/schema.json",
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "title": "Model",
    "description": "Testing",
    "type": "object",
    "properties": {
        "property_a": {
            "type": "integer",
            "default": 5
        }
    },
    "required": ["property_a"]
}
```

```bash
datamodel-codegen --input schema.json \
    --input-file-type jsonschema \
    --disable-timestamp \
    --use-default \
    --output schema.py
```

schema.py
```python
# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Model(BaseModel):
    property_a: Optional[int] = 5
```

Even though "property_a" was marked as required it's listed as an Optional property in the model because the property also has a default value of 5.

Because of this mypy or other type hinting tools would complain if you did as below as "property_a" could also be `None`

```python

stuff = Model()
print(stuff.property_a + 3)
```

**Describe the solution you'd like**
I think it would make more sense if the properties marked as required never got the `Optional`, or that there at least existed a way to make it behave in this way.

**Describe alternatives you've considered**
Current workaround is to reassign the default value in code or create another variable

**Comment by zcherry17** [comment]
Running into this as well. Would love to see a fix.

**Comment by koxudaxi** [comment]
@ogenstad @zcherry17 @skilkis 
I'm sorry for my late reply.
Could you please try ` --strict-nullable` ?

```python

class Model(BaseModel):
    property_a: int = 5
```
You can get the model.

**Comment by ogenstad** [comment]
Thanks, that works! I don't really remember as it was a while ago but I probably just assumed that a --use-default would be enough given that the property was already marked as being required.
