### ISSUE TITLE
JsonSchemaObject's additionalProperties may be boolean

### ISSUE THREAD

**Issue by stevesimmons** [koxudaxi/datamodel-code-generator#82]
The OpenAPI v3.0.1 schema allows JsonSchemaObject's additionalProperties to be a boolean or a JsonSchemaObject. 

Specifically, the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject) says:  
> "additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema."

However the definition at L51 of jsonschema.py has:  
`additionalProperties: Optional['JsonSchemaObject']`.

This fails on schemas with `additionalProperties: false`.

Suggested fix is to change L51 of jsonschema.py to:  
`additionalProperties: Union['JsonSchemaObject', bool, None]`.

**Comment by koxudaxi** [comment]
@stevesimmons 
Thank you for posting a feature request.
I have released a new version as `0.2.15`.
If `object` has `additionalProperties` attribute and which is True, then the code-generator add Extra.allow on BaseModel's Config.
This option allows passing additional properties on the pydantic model.
