### ISSUE TITLE
Object properties missing when JSON Schema uses anyOf

### ISSUE THREAD

**Issue by franga2000** [koxudaxi/datamodel-code-generator#869]
**Describe the bug**

When a JSON Schema object uses `anyOf` containing a subset of the object's `properties`, only the fields in the `anyOf` objects are generated, ignoring all the fields in the object itself. 

In the specific schema linked below, the intention seems to be to be that if `station_id` is given, `lat` and `lon` are not required, otherwise they are. I'm not sure the wanted behaviour is to-spec and even [Atlassian's schema viewer](https://json-schema.app) doesn't handle it that way, but its interpretation (quoted and linked below) seems to be the more correct way of handling this situation (the presence of `anyOf` and `properties`, which the spec does allow) and actually produces a useful model.

**To Reproduce**

Example schema:
GBFS v2.3 [free_bikes_status.json](https://github.com/MobilityData/gbfs-json-schema/blob/2cc87f07b8dcdb8a930e0fed6df267c0a3181a88/v2.3/free_bike_status.json#L126-L143) (with the problematic `anyOf` highlighted)

Used commandline:
```
$ datamodel-codegen --input "free_bike_status.json" --output "free_bike_status.py"
```

**Expected behavior**

The way Atlassian's schema viewer does it ([direct link](https://json-schema.app/view/%23/%23%2Fproperties%2Fdata/%23%2Fproperties%2Fdata%2Fproperties%2Fbikes%2Fitems?url=https%3A%2F%2Fraw.githubusercontent.com%2FMobilityData%2Fgbfs-json-schema%2F2cc87f07b8dcdb8a930e0fed6df267c0a3181a88%2Fv2.3%2Ffree_bike_status.json)) - all the fields (`is_reserved`, `is_disabled`...) are present, but additional validation is added according to the `anyOf`:

> This type has all of the properties below, but must also match this type:
>     anyOf required: lat ∩ lon, object
> [then list all the defined properties]

Although I'm not too familiar with this part of the spec, this seems to be the more correct way of handling the case where an object contains both `anyOf` and its own `properties` - parse both. Looking at the [relevant code](https://github.com/koxudaxi/datamodel-code-generator/blob/master/datamodel_code_generator/parser/jsonschema.py#L653-L658), this case seems to be ignored and the presence of `anyOf` makes the parser skip parsing the `properties` all together.

**Version:**
 - Python version: 3.10.7
 - datamodel-code-generator version: 0.13.11

**Comment by koxudaxi** [comment]
@franga2000 
I'm sorry for my too-late reply.
I have released a fixed version as 0.16.0.
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.16.0
This version can parse properties with anyOf.
But, It doesn't provide a validator for the actual `anyOf` spec.

Thank you very much!!
