### ISSUE TITLE
Does not support boolean JSON Schemas (trivially true or false)

### ISSUE THREAD

**Issue by apirogov** [koxudaxi/datamodel-code-generator#870]
**Describe the bug**

Currently, the tool does not support boolean-valued JSON Schemas, even though booleans are valid schemas.

**To Reproduce**

Example schema `test.json`:

```json
{
  "type": "object",
  "properties": {
    "field": true
  }
}
```

Used commandline:
```
$ datamodel-codegen --input test.json
```
Result:

```
...
pydantic.error_wrappers.ValidationError: 1 validation error for JsonSchemaObject
properties -> field
  value is not a valid dict (type=type_error.dict)
```

**Expected behavior**

Should accept the schema. It does work fine when substituting all `true` schemas with `{}`.

Why am I even using `true` schemas: To express that a field is accepted, without checking it, even if I would set `additionalProperties = False`.

Would be great if this could be fixed! :-)

**Version:**
 - datamodel-code-generator version: 0.13.1

**Comment by koxudaxi** [comment]
version 0.13.2 has been released with the feature.
Thank you very much.
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.13.2
