### ISSUE TITLE
Same definition in different JSON schemas adds unnecessary suffix + OS inconsistency

### ISSUE THREAD

**Issue by pmbrull** [koxudaxi/datamodel-code-generator#961]
**Describe the bug**
If we have a `bar.json` and `foo.json`, both containing the same definition name, we'll get `DefinitionName` in one module and `DefinitionName1` in the other. This should not be necessary, as the namespace for both imports would already be different.

What makes it tricky is that in macOS we get the number in the suffix, but not on ubuntu. This causes issues on our CI pipelines and we got some unexpected bugs as the imports we ship in the project might not exist if the package is built in GitHub actions.

**To Reproduce**

in `bar.json`
```json
{
  "$id": "bar.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Bar",
  "type": "object",
  "definitions": {
    "logLevels": {
      "description": "Supported logging levels",
      "type": "string"
    }
  }
}
```

in `foo.json`
```json
{
  "$id": "foo.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Foo",
  "type": "object",
  "definitions": {
    "logLevels": {
      "description": "Supported logging levels",
      "type": "string"
    }
  }
}
```

Used commandline:
```
$ datamodel-codegen --input ingestion/ --input-file-type jsonschema --output generated --set-default-enum-member
```

We get in `bar.py`
```python
class LogLevels1(BaseModel):
    __root__: str = Field(..., description='Supported logging levels')
```

and `foo.py`
```python
class LogLevels(BaseModel):
    __root__: str = Field(..., description='Supported logging levels')
```

**Expected behavior**

A definition in different JSON Schemas should keep the original name. The import namespace would already take care of not having a clash.

**Version:**
 - OS: [e.g. iOS] Macos Ventura
 - Python version: 3.9
 - datamodel-code-generator version: [e.g. 22] 0.13.3

**Additional context**

Our solution for now is to rename definitions to force different generations, but it's not the most elegant solution if, for example, we want to have a `type` field in `table.json` and `topic.json`, etc.

Thanks!

**Comment by koxudaxi** [comment]
@pmbrull 
I have released the PR as `0.15.0`
Thank you very much!!
